// Données Gen 1-3 (#1-386) : noms et types officiels en FR/EN/ES/DE, récupérés
// depuis le miroir statique de PokeAPI (PokeAPI/api-data sur GitHub).
const POKEMON_GEN1 = [
  { id: 1, gen: 1, names: { fr: "Bulbizarre", en: "Bulbasaur", es: "Bulbasaur", de: "Bisasam" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"], de: ["Pflanze", "Gift"] } },
  { id: 2, gen: 1, names: { fr: "Herbizarre", en: "Ivysaur", es: "Ivysaur", de: "Bisaknosp" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"], de: ["Pflanze", "Gift"] } },
  { id: 3, gen: 1, names: { fr: "Florizarre", en: "Venusaur", es: "Venusaur", de: "Bisaflor" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"], de: ["Pflanze", "Gift"] } },
  { id: 4, gen: 1, names: { fr: "Salamèche", en: "Charmander", es: "Charmander", de: "Glumanda" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 5, gen: 1, names: { fr: "Reptincel", en: "Charmeleon", es: "Charmeleon", de: "Glutexo" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 6, gen: 1, names: { fr: "Dracaufeu", en: "Charizard", es: "Charizard", de: "Glurak" }, types: { fr: ["Feu", "Vol"], en: ["Fire", "Flying"], es: ["Fuego", "Volador"], de: ["Feuer", "Flug"] } },
  { id: 7, gen: 1, names: { fr: "Carapuce", en: "Squirtle", es: "Squirtle", de: "Schiggy" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 8, gen: 1, names: { fr: "Carabaffe", en: "Wartortle", es: "Wartortle", de: "Schillok" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 9, gen: 1, names: { fr: "Tortank", en: "Blastoise", es: "Blastoise", de: "Turtok" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 10, gen: 1, names: { fr: "Chenipan", en: "Caterpie", es: "Caterpie", de: "Raupy" }, types: { fr: ["Insecte"], en: ["Bug"], es: ["Bicho"], de: ["Käfer"] } },
  { id: 11, gen: 1, names: { fr: "Chrysacier", en: "Metapod", es: "Metapod", de: "Safcon" }, types: { fr: ["Insecte"], en: ["Bug"], es: ["Bicho"], de: ["Käfer"] } },
  { id: 12, gen: 1, names: { fr: "Papilusion", en: "Butterfree", es: "Butterfree", de: "Smettbo" }, types: { fr: ["Insecte", "Vol"], en: ["Bug", "Flying"], es: ["Bicho", "Volador"], de: ["Käfer", "Flug"] } },
  { id: 13, gen: 1, names: { fr: "Aspicot", en: "Weedle", es: "Weedle", de: "Hornliu" }, types: { fr: ["Insecte", "Poison"], en: ["Bug", "Poison"], es: ["Bicho", "Veneno"], de: ["Käfer", "Gift"] } },
  { id: 14, gen: 1, names: { fr: "Coconfort", en: "Kakuna", es: "Kakuna", de: "Kokuna" }, types: { fr: ["Insecte", "Poison"], en: ["Bug", "Poison"], es: ["Bicho", "Veneno"], de: ["Käfer", "Gift"] } },
  { id: 15, gen: 1, names: { fr: "Dardargnan", en: "Beedrill", es: "Beedrill", de: "Bibor" }, types: { fr: ["Insecte", "Poison"], en: ["Bug", "Poison"], es: ["Bicho", "Veneno"], de: ["Käfer", "Gift"] } },
  { id: 16, gen: 1, names: { fr: "Roucool", en: "Pidgey", es: "Pidgey", de: "Taubsi" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"], de: ["Normal", "Flug"] } },
  { id: 17, gen: 1, names: { fr: "Roucoups", en: "Pidgeotto", es: "Pidgeotto", de: "Tauboga" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"], de: ["Normal", "Flug"] } },
  { id: 18, gen: 1, names: { fr: "Roucarnage", en: "Pidgeot", es: "Pidgeot", de: "Tauboss" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"], de: ["Normal", "Flug"] } },
  { id: 19, gen: 1, names: { fr: "Rattata", en: "Rattata", es: "Rattata", de: "Rattfratz" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 20, gen: 1, names: { fr: "Rattatac", en: "Raticate", es: "Raticate", de: "Rattikarl" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 21, gen: 1, names: { fr: "Piafabec", en: "Spearow", es: "Spearow", de: "Habitak" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"], de: ["Normal", "Flug"] } },
  { id: 22, gen: 1, names: { fr: "Rapasdepic", en: "Fearow", es: "Fearow", de: "Ibitak" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"], de: ["Normal", "Flug"] } },
  { id: 23, gen: 1, names: { fr: "Abo", en: "Ekans", es: "Ekans", de: "Rettan" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"], de: ["Gift"] } },
  { id: 24, gen: 1, names: { fr: "Arbok", en: "Arbok", es: "Arbok", de: "Arbok" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"], de: ["Gift"] } },
  { id: 25, gen: 1, names: { fr: "Pikachu", en: "Pikachu", es: "Pikachu", de: "Pikachu" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"], de: ["Elektro"] } },
  { id: 26, gen: 1, names: { fr: "Raichu", en: "Raichu", es: "Raichu", de: "Raichu" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"], de: ["Elektro"] } },
  { id: 27, gen: 1, names: { fr: "Sabelette", en: "Sandshrew", es: "Sandshrew", de: "Sandan" }, types: { fr: ["Sol"], en: ["Ground"], es: ["Tierra"], de: ["Boden"] } },
  { id: 28, gen: 1, names: { fr: "Sablaireau", en: "Sandslash", es: "Sandslash", de: "Sandamer" }, types: { fr: ["Sol"], en: ["Ground"], es: ["Tierra"], de: ["Boden"] } },
  { id: 29, gen: 1, names: { fr: "Nidoran♀", en: "Nidoran♀", es: "Nidoran♀", de: "Nidoran♀" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"], de: ["Gift"] } },
  { id: 30, gen: 1, names: { fr: "Nidorina", en: "Nidorina", es: "Nidorina", de: "Nidorina" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"], de: ["Gift"] } },
  { id: 31, gen: 1, names: { fr: "Nidoqueen", en: "Nidoqueen", es: "Nidoqueen", de: "Nidoqueen" }, types: { fr: ["Poison", "Sol"], en: ["Poison", "Ground"], es: ["Veneno", "Tierra"], de: ["Gift", "Boden"] } },
  { id: 32, gen: 1, names: { fr: "Nidoran♂", en: "Nidoran♂", es: "Nidoran♂", de: "Nidoran♂" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"], de: ["Gift"] } },
  { id: 33, gen: 1, names: { fr: "Nidorino", en: "Nidorino", es: "Nidorino", de: "Nidorino" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"], de: ["Gift"] } },
  { id: 34, gen: 1, names: { fr: "Nidoking", en: "Nidoking", es: "Nidoking", de: "Nidoking" }, types: { fr: ["Poison", "Sol"], en: ["Poison", "Ground"], es: ["Veneno", "Tierra"], de: ["Gift", "Boden"] } },
  { id: 35, gen: 1, names: { fr: "Mélofée", en: "Clefairy", es: "Clefairy", de: "Piepi" }, types: { fr: ["Fée"], en: ["Fairy"], es: ["Hada"], de: ["Fee"] } },
  { id: 36, gen: 1, names: { fr: "Mélodelfe", en: "Clefable", es: "Clefable", de: "Pixi" }, types: { fr: ["Fée"], en: ["Fairy"], es: ["Hada"], de: ["Fee"] } },
  { id: 37, gen: 1, names: { fr: "Goupix", en: "Vulpix", es: "Vulpix", de: "Vulpix" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 38, gen: 1, names: { fr: "Feunard", en: "Ninetales", es: "Ninetales", de: "Vulnona" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 39, gen: 1, names: { fr: "Rondoudou", en: "Jigglypuff", es: "Jigglypuff", de: "Pummeluff" }, types: { fr: ["Normal", "Fée"], en: ["Normal", "Fairy"], es: ["Normal", "Hada"], de: ["Normal", "Fee"] } },
  { id: 40, gen: 1, names: { fr: "Grodoudou", en: "Wigglytuff", es: "Wigglytuff", de: "Knuddeluff" }, types: { fr: ["Normal", "Fée"], en: ["Normal", "Fairy"], es: ["Normal", "Hada"], de: ["Normal", "Fee"] } },
  { id: 41, gen: 1, names: { fr: "Nosferapti", en: "Zubat", es: "Zubat", de: "Zubat" }, types: { fr: ["Poison", "Vol"], en: ["Poison", "Flying"], es: ["Veneno", "Volador"], de: ["Gift", "Flug"] } },
  { id: 42, gen: 1, names: { fr: "Nosferalto", en: "Golbat", es: "Golbat", de: "Golbat" }, types: { fr: ["Poison", "Vol"], en: ["Poison", "Flying"], es: ["Veneno", "Volador"], de: ["Gift", "Flug"] } },
  { id: 43, gen: 1, names: { fr: "Mystherbe", en: "Oddish", es: "Oddish", de: "Myrapla" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"], de: ["Pflanze", "Gift"] } },
  { id: 44, gen: 1, names: { fr: "Ortide", en: "Gloom", es: "Gloom", de: "Duflor" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"], de: ["Pflanze", "Gift"] } },
  { id: 45, gen: 1, names: { fr: "Rafflesia", en: "Vileplume", es: "Vileplume", de: "Giflor" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"], de: ["Pflanze", "Gift"] } },
  { id: 46, gen: 1, names: { fr: "Paras", en: "Paras", es: "Paras", de: "Paras" }, types: { fr: ["Insecte", "Plante"], en: ["Bug", "Grass"], es: ["Bicho", "Planta"], de: ["Käfer", "Pflanze"] } },
  { id: 47, gen: 1, names: { fr: "Parasect", en: "Parasect", es: "Parasect", de: "Parasek" }, types: { fr: ["Insecte", "Plante"], en: ["Bug", "Grass"], es: ["Bicho", "Planta"], de: ["Käfer", "Pflanze"] } },
  { id: 48, gen: 1, names: { fr: "Mimitoss", en: "Venonat", es: "Venonat", de: "Bluzuk" }, types: { fr: ["Insecte", "Poison"], en: ["Bug", "Poison"], es: ["Bicho", "Veneno"], de: ["Käfer", "Gift"] } },
  { id: 49, gen: 1, names: { fr: "Aéromite", en: "Venomoth", es: "Venomoth", de: "Omot" }, types: { fr: ["Insecte", "Poison"], en: ["Bug", "Poison"], es: ["Bicho", "Veneno"], de: ["Käfer", "Gift"] } },
  { id: 50, gen: 1, names: { fr: "Taupiqueur", en: "Diglett", es: "Diglett", de: "Digda" }, types: { fr: ["Sol"], en: ["Ground"], es: ["Tierra"], de: ["Boden"] } },
  { id: 51, gen: 1, names: { fr: "Triopikeur", en: "Dugtrio", es: "Dugtrio", de: "Digdri" }, types: { fr: ["Sol"], en: ["Ground"], es: ["Tierra"], de: ["Boden"] } },
  { id: 52, gen: 1, names: { fr: "Miaouss", en: "Meowth", es: "Meowth", de: "Mauzi" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 53, gen: 1, names: { fr: "Persian", en: "Persian", es: "Persian", de: "Snobilikat" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 54, gen: 1, names: { fr: "Psykokwak", en: "Psyduck", es: "Psyduck", de: "Enton" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 55, gen: 1, names: { fr: "Akwakwak", en: "Golduck", es: "Golduck", de: "Entoron" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 56, gen: 1, names: { fr: "Férosinge", en: "Mankey", es: "Mankey", de: "Menki" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"], de: ["Kampf"] } },
  { id: 57, gen: 1, names: { fr: "Colossinge", en: "Primeape", es: "Primeape", de: "Rasaff" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"], de: ["Kampf"] } },
  { id: 58, gen: 1, names: { fr: "Caninos", en: "Growlithe", es: "Growlithe", de: "Fukano" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 59, gen: 1, names: { fr: "Arcanin", en: "Arcanine", es: "Arcanine", de: "Arkani" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 60, gen: 1, names: { fr: "Ptitard", en: "Poliwag", es: "Poliwag", de: "Quapsel" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 61, gen: 1, names: { fr: "Têtarte", en: "Poliwhirl", es: "Poliwhirl", de: "Quaputzi" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 62, gen: 1, names: { fr: "Tartard", en: "Poliwrath", es: "Poliwrath", de: "Quappo" }, types: { fr: ["Eau", "Combat"], en: ["Water", "Fighting"], es: ["Agua", "Lucha"], de: ["Wasser", "Kampf"] } },
  { id: 63, gen: 1, names: { fr: "Abra", en: "Abra", es: "Abra", de: "Abra" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"], de: ["Psycho"] } },
  { id: 64, gen: 1, names: { fr: "Kadabra", en: "Kadabra", es: "Kadabra", de: "Kadabra" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"], de: ["Psycho"] } },
  { id: 65, gen: 1, names: { fr: "Alakazam", en: "Alakazam", es: "Alakazam", de: "Simsala" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"], de: ["Psycho"] } },
  { id: 66, gen: 1, names: { fr: "Machoc", en: "Machop", es: "Machop", de: "Machollo" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"], de: ["Kampf"] } },
  { id: 67, gen: 1, names: { fr: "Machopeur", en: "Machoke", es: "Machoke", de: "Maschock" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"], de: ["Kampf"] } },
  { id: 68, gen: 1, names: { fr: "Mackogneur", en: "Machamp", es: "Machamp", de: "Machomei" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"], de: ["Kampf"] } },
  { id: 69, gen: 1, names: { fr: "Chétiflor", en: "Bellsprout", es: "Bellsprout", de: "Knofensa" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"], de: ["Pflanze", "Gift"] } },
  { id: 70, gen: 1, names: { fr: "Boustiflor", en: "Weepinbell", es: "Weepinbell", de: "Ultrigaria" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"], de: ["Pflanze", "Gift"] } },
  { id: 71, gen: 1, names: { fr: "Empiflor", en: "Victreebel", es: "Victreebel", de: "Sarzenia" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"], de: ["Pflanze", "Gift"] } },
  { id: 72, gen: 1, names: { fr: "Tentacool", en: "Tentacool", es: "Tentacool", de: "Tentacha" }, types: { fr: ["Eau", "Poison"], en: ["Water", "Poison"], es: ["Agua", "Veneno"], de: ["Wasser", "Gift"] } },
  { id: 73, gen: 1, names: { fr: "Tentacruel", en: "Tentacruel", es: "Tentacruel", de: "Tentoxa" }, types: { fr: ["Eau", "Poison"], en: ["Water", "Poison"], es: ["Agua", "Veneno"], de: ["Wasser", "Gift"] } },
  { id: 74, gen: 1, names: { fr: "Racaillou", en: "Geodude", es: "Geodude", de: "Kleinstein" }, types: { fr: ["Roche", "Sol"], en: ["Rock", "Ground"], es: ["Roca", "Tierra"], de: ["Gestein", "Boden"] } },
  { id: 75, gen: 1, names: { fr: "Gravalanch", en: "Graveler", es: "Graveler", de: "Georok" }, types: { fr: ["Roche", "Sol"], en: ["Rock", "Ground"], es: ["Roca", "Tierra"], de: ["Gestein", "Boden"] } },
  { id: 76, gen: 1, names: { fr: "Grolem", en: "Golem", es: "Golem", de: "Geowaz" }, types: { fr: ["Roche", "Sol"], en: ["Rock", "Ground"], es: ["Roca", "Tierra"], de: ["Gestein", "Boden"] } },
  { id: 77, gen: 1, names: { fr: "Ponyta", en: "Ponyta", es: "Ponyta", de: "Ponita" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 78, gen: 1, names: { fr: "Galopa", en: "Rapidash", es: "Rapidash", de: "Gallopa" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 79, gen: 1, names: { fr: "Ramoloss", en: "Slowpoke", es: "Slowpoke", de: "Flegmon" }, types: { fr: ["Eau", "Psy"], en: ["Water", "Psychic"], es: ["Agua", "Psíquico"], de: ["Wasser", "Psycho"] } },
  { id: 80, gen: 1, names: { fr: "Flagadoss", en: "Slowbro", es: "Slowbro", de: "Lahmus" }, types: { fr: ["Eau", "Psy"], en: ["Water", "Psychic"], es: ["Agua", "Psíquico"], de: ["Wasser", "Psycho"] } },
  { id: 81, gen: 1, names: { fr: "Magnéti", en: "Magnemite", es: "Magnemite", de: "Magnetilo" }, types: { fr: ["Électrik", "Acier"], en: ["Electric", "Steel"], es: ["Eléctrico", "Acero"], de: ["Elektro", "Stahl"] } },
  { id: 82, gen: 1, names: { fr: "Magnéton", en: "Magneton", es: "Magneton", de: "Magneton" }, types: { fr: ["Électrik", "Acier"], en: ["Electric", "Steel"], es: ["Eléctrico", "Acero"], de: ["Elektro", "Stahl"] } },
  { id: 83, gen: 1, names: { fr: "Canarticho", en: "Farfetch’d", es: "Farfetch’d", de: "Porenta" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"], de: ["Normal", "Flug"] } },
  { id: 84, gen: 1, names: { fr: "Doduo", en: "Doduo", es: "Doduo", de: "Dodu" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"], de: ["Normal", "Flug"] } },
  { id: 85, gen: 1, names: { fr: "Dodrio", en: "Dodrio", es: "Dodrio", de: "Dodri" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"], de: ["Normal", "Flug"] } },
  { id: 86, gen: 1, names: { fr: "Otaria", en: "Seel", es: "Seel", de: "Jurob" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 87, gen: 1, names: { fr: "Lamantine", en: "Dewgong", es: "Dewgong", de: "Jugong" }, types: { fr: ["Eau", "Glace"], en: ["Water", "Ice"], es: ["Agua", "Hielo"], de: ["Wasser", "Eis"] } },
  { id: 88, gen: 1, names: { fr: "Tadmorv", en: "Grimer", es: "Grimer", de: "Sleima" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"], de: ["Gift"] } },
  { id: 89, gen: 1, names: { fr: "Grotadmorv", en: "Muk", es: "Muk", de: "Sleimok" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"], de: ["Gift"] } },
  { id: 90, gen: 1, names: { fr: "Kokiyas", en: "Shellder", es: "Shellder", de: "Muschas" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 91, gen: 1, names: { fr: "Crustabri", en: "Cloyster", es: "Cloyster", de: "Austos" }, types: { fr: ["Eau", "Glace"], en: ["Water", "Ice"], es: ["Agua", "Hielo"], de: ["Wasser", "Eis"] } },
  { id: 92, gen: 1, names: { fr: "Fantominus", en: "Gastly", es: "Gastly", de: "Nebulak" }, types: { fr: ["Spectre", "Poison"], en: ["Ghost", "Poison"], es: ["Fantasma", "Veneno"], de: ["Geist", "Gift"] } },
  { id: 93, gen: 1, names: { fr: "Spectrum", en: "Haunter", es: "Haunter", de: "Alpollo" }, types: { fr: ["Spectre", "Poison"], en: ["Ghost", "Poison"], es: ["Fantasma", "Veneno"], de: ["Geist", "Gift"] } },
  { id: 94, gen: 1, names: { fr: "Ectoplasma", en: "Gengar", es: "Gengar", de: "Gengar" }, types: { fr: ["Spectre", "Poison"], en: ["Ghost", "Poison"], es: ["Fantasma", "Veneno"], de: ["Geist", "Gift"] } },
  { id: 95, gen: 1, names: { fr: "Onix", en: "Onix", es: "Onix", de: "Onix" }, types: { fr: ["Roche", "Sol"], en: ["Rock", "Ground"], es: ["Roca", "Tierra"], de: ["Gestein", "Boden"] } },
  { id: 96, gen: 1, names: { fr: "Soporifik", en: "Drowzee", es: "Drowzee", de: "Traumato" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"], de: ["Psycho"] } },
  { id: 97, gen: 1, names: { fr: "Hypnomade", en: "Hypno", es: "Hypno", de: "Hypno" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"], de: ["Psycho"] } },
  { id: 98, gen: 1, names: { fr: "Krabby", en: "Krabby", es: "Krabby", de: "Krabby" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 99, gen: 1, names: { fr: "Krabboss", en: "Kingler", es: "Kingler", de: "Kingler" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 100, gen: 1, names: { fr: "Voltorbe", en: "Voltorb", es: "Voltorb", de: "Voltobal" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"], de: ["Elektro"] } },
  { id: 101, gen: 1, names: { fr: "Électrode", en: "Electrode", es: "Electrode", de: "Lektrobal" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"], de: ["Elektro"] } },
  { id: 102, gen: 1, names: { fr: "Noeunoeuf", en: "Exeggcute", es: "Exeggcute", de: "Owei" }, types: { fr: ["Plante", "Psy"], en: ["Grass", "Psychic"], es: ["Planta", "Psíquico"], de: ["Pflanze", "Psycho"] } },
  { id: 103, gen: 1, names: { fr: "Noadkoko", en: "Exeggutor", es: "Exeggutor", de: "Kokowei" }, types: { fr: ["Plante", "Psy"], en: ["Grass", "Psychic"], es: ["Planta", "Psíquico"], de: ["Pflanze", "Psycho"] } },
  { id: 104, gen: 1, names: { fr: "Osselait", en: "Cubone", es: "Cubone", de: "Tragosso" }, types: { fr: ["Sol"], en: ["Ground"], es: ["Tierra"], de: ["Boden"] } },
  { id: 105, gen: 1, names: { fr: "Ossatueur", en: "Marowak", es: "Marowak", de: "Knogga" }, types: { fr: ["Sol"], en: ["Ground"], es: ["Tierra"], de: ["Boden"] } },
  { id: 106, gen: 1, names: { fr: "Kicklee", en: "Hitmonlee", es: "Hitmonlee", de: "Kicklee" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"], de: ["Kampf"] } },
  { id: 107, gen: 1, names: { fr: "Tygnon", en: "Hitmonchan", es: "Hitmonchan", de: "Nockchan" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"], de: ["Kampf"] } },
  { id: 108, gen: 1, names: { fr: "Excelangue", en: "Lickitung", es: "Lickitung", de: "Schlurp" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 109, gen: 1, names: { fr: "Smogo", en: "Koffing", es: "Koffing", de: "Smogon" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"], de: ["Gift"] } },
  { id: 110, gen: 1, names: { fr: "Smogogo", en: "Weezing", es: "Weezing", de: "Smogmog" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"], de: ["Gift"] } },
  { id: 111, gen: 1, names: { fr: "Rhinocorne", en: "Rhyhorn", es: "Rhyhorn", de: "Rihorn" }, types: { fr: ["Sol", "Roche"], en: ["Ground", "Rock"], es: ["Tierra", "Roca"], de: ["Boden", "Gestein"] } },
  { id: 112, gen: 1, names: { fr: "Rhinoféros", en: "Rhydon", es: "Rhydon", de: "Rizeros" }, types: { fr: ["Sol", "Roche"], en: ["Ground", "Rock"], es: ["Tierra", "Roca"], de: ["Boden", "Gestein"] } },
  { id: 113, gen: 1, names: { fr: "Leveinard", en: "Chansey", es: "Chansey", de: "Chaneira" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 114, gen: 1, names: { fr: "Saquedeneu", en: "Tangela", es: "Tangela", de: "Tangela" }, types: { fr: ["Plante"], en: ["Grass"], es: ["Planta"], de: ["Pflanze"] } },
  { id: 115, gen: 1, names: { fr: "Kangourex", en: "Kangaskhan", es: "Kangaskhan", de: "Kangama" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 116, gen: 1, names: { fr: "Hypotrempe", en: "Horsea", es: "Horsea", de: "Seeper" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 117, gen: 1, names: { fr: "Hypocéan", en: "Seadra", es: "Seadra", de: "Seemon" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 118, gen: 1, names: { fr: "Poissirène", en: "Goldeen", es: "Goldeen", de: "Goldini" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 119, gen: 1, names: { fr: "Poissoroy", en: "Seaking", es: "Seaking", de: "Golking" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 120, gen: 1, names: { fr: "Stari", en: "Staryu", es: "Staryu", de: "Sterndu" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 121, gen: 1, names: { fr: "Staross", en: "Starmie", es: "Starmie", de: "Starmie" }, types: { fr: ["Eau", "Psy"], en: ["Water", "Psychic"], es: ["Agua", "Psíquico"], de: ["Wasser", "Psycho"] } },
  { id: 122, gen: 1, names: { fr: "M. Mime", en: "Mr. Mime", es: "Mr. Mime", de: "Pantimos" }, types: { fr: ["Psy", "Fée"], en: ["Psychic", "Fairy"], es: ["Psíquico", "Hada"], de: ["Psycho", "Fee"] } },
  { id: 123, gen: 1, names: { fr: "Insécateur", en: "Scyther", es: "Scyther", de: "Sichlor" }, types: { fr: ["Insecte", "Vol"], en: ["Bug", "Flying"], es: ["Bicho", "Volador"], de: ["Käfer", "Flug"] } },
  { id: 124, gen: 1, names: { fr: "Lippoutou", en: "Jynx", es: "Jynx", de: "Rossana" }, types: { fr: ["Glace", "Psy"], en: ["Ice", "Psychic"], es: ["Hielo", "Psíquico"], de: ["Eis", "Psycho"] } },
  { id: 125, gen: 1, names: { fr: "Élektek", en: "Electabuzz", es: "Electabuzz", de: "Elektek" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"], de: ["Elektro"] } },
  { id: 126, gen: 1, names: { fr: "Magmar", en: "Magmar", es: "Magmar", de: "Magmar" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 127, gen: 1, names: { fr: "Scarabrute", en: "Pinsir", es: "Pinsir", de: "Pinsir" }, types: { fr: ["Insecte"], en: ["Bug"], es: ["Bicho"], de: ["Käfer"] } },
  { id: 128, gen: 1, names: { fr: "Tauros", en: "Tauros", es: "Tauros", de: "Tauros" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 129, gen: 1, names: { fr: "Magicarpe", en: "Magikarp", es: "Magikarp", de: "Karpador" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 130, gen: 1, names: { fr: "Léviator", en: "Gyarados", es: "Gyarados", de: "Garados" }, types: { fr: ["Eau", "Vol"], en: ["Water", "Flying"], es: ["Agua", "Volador"], de: ["Wasser", "Flug"] } },
  { id: 131, gen: 1, names: { fr: "Lokhlass", en: "Lapras", es: "Lapras", de: "Lapras" }, types: { fr: ["Eau", "Glace"], en: ["Water", "Ice"], es: ["Agua", "Hielo"], de: ["Wasser", "Eis"] } },
  { id: 132, gen: 1, names: { fr: "Métamorph", en: "Ditto", es: "Ditto", de: "Ditto" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 133, gen: 1, names: { fr: "Évoli", en: "Eevee", es: "Eevee", de: "Evoli" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 134, gen: 1, names: { fr: "Aquali", en: "Vaporeon", es: "Vaporeon", de: "Aquana" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 135, gen: 1, names: { fr: "Voltali", en: "Jolteon", es: "Jolteon", de: "Blitza" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"], de: ["Elektro"] } },
  { id: 136, gen: 1, names: { fr: "Pyroli", en: "Flareon", es: "Flareon", de: "Flamara" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 137, gen: 1, names: { fr: "Porygon", en: "Porygon", es: "Porygon", de: "Porygon" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 138, gen: 1, names: { fr: "Amonita", en: "Omanyte", es: "Omanyte", de: "Amonitas" }, types: { fr: ["Roche", "Eau"], en: ["Rock", "Water"], es: ["Roca", "Agua"], de: ["Gestein", "Wasser"] } },
  { id: 139, gen: 1, names: { fr: "Amonistar", en: "Omastar", es: "Omastar", de: "Amoroso" }, types: { fr: ["Roche", "Eau"], en: ["Rock", "Water"], es: ["Roca", "Agua"], de: ["Gestein", "Wasser"] } },
  { id: 140, gen: 1, names: { fr: "Kabuto", en: "Kabuto", es: "Kabuto", de: "Kabuto" }, types: { fr: ["Roche", "Eau"], en: ["Rock", "Water"], es: ["Roca", "Agua"], de: ["Gestein", "Wasser"] } },
  { id: 141, gen: 1, names: { fr: "Kabutops", en: "Kabutops", es: "Kabutops", de: "Kabutops" }, types: { fr: ["Roche", "Eau"], en: ["Rock", "Water"], es: ["Roca", "Agua"], de: ["Gestein", "Wasser"] } },
  { id: 142, gen: 1, names: { fr: "Ptéra", en: "Aerodactyl", es: "Aerodactyl", de: "Aerodactyl" }, types: { fr: ["Roche", "Vol"], en: ["Rock", "Flying"], es: ["Roca", "Volador"], de: ["Gestein", "Flug"] } },
  { id: 143, gen: 1, names: { fr: "Ronflex", en: "Snorlax", es: "Snorlax", de: "Relaxo" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 144, gen: 1, names: { fr: "Artikodin", en: "Articuno", es: "Articuno", de: "Arktos" }, types: { fr: ["Glace", "Vol"], en: ["Ice", "Flying"], es: ["Hielo", "Volador"], de: ["Eis", "Flug"] } },
  { id: 145, gen: 1, names: { fr: "Électhor", en: "Zapdos", es: "Zapdos", de: "Zapdos" }, types: { fr: ["Électrik", "Vol"], en: ["Electric", "Flying"], es: ["Eléctrico", "Volador"], de: ["Elektro", "Flug"] } },
  { id: 146, gen: 1, names: { fr: "Sulfura", en: "Moltres", es: "Moltres", de: "Lavados" }, types: { fr: ["Feu", "Vol"], en: ["Fire", "Flying"], es: ["Fuego", "Volador"], de: ["Feuer", "Flug"] } },
  { id: 147, gen: 1, names: { fr: "Minidraco", en: "Dratini", es: "Dratini", de: "Dratini" }, types: { fr: ["Dragon"], en: ["Dragon"], es: ["Dragón"], de: ["Drache"] } },
  { id: 148, gen: 1, names: { fr: "Draco", en: "Dragonair", es: "Dragonair", de: "Dragonir" }, types: { fr: ["Dragon"], en: ["Dragon"], es: ["Dragón"], de: ["Drache"] } },
  { id: 149, gen: 1, names: { fr: "Dracolosse", en: "Dragonite", es: "Dragonite", de: "Dragoran" }, types: { fr: ["Dragon", "Vol"], en: ["Dragon", "Flying"], es: ["Dragón", "Volador"], de: ["Drache", "Flug"] } },
  { id: 150, gen: 1, names: { fr: "Mewtwo", en: "Mewtwo", es: "Mewtwo", de: "Mewtu" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"], de: ["Psycho"] } },
  { id: 151, gen: 1, names: { fr: "Mew", en: "Mew", es: "Mew", de: "Mew" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"], de: ["Psycho"] } },
  { id: 152, gen: 2, names: { fr: "Germignon", en: "Chikorita", es: "Chikorita", de: "Endivie" }, types: { fr: ["Plante"], en: ["Grass"], es: ["Planta"], de: ["Pflanze"] } },
  { id: 153, gen: 2, names: { fr: "Macronium", en: "Bayleef", es: "Bayleef", de: "Lorblatt" }, types: { fr: ["Plante"], en: ["Grass"], es: ["Planta"], de: ["Pflanze"] } },
  { id: 154, gen: 2, names: { fr: "Méganium", en: "Meganium", es: "Meganium", de: "Meganie" }, types: { fr: ["Plante"], en: ["Grass"], es: ["Planta"], de: ["Pflanze"] } },
  { id: 155, gen: 2, names: { fr: "Héricendre", en: "Cyndaquil", es: "Cyndaquil", de: "Feurigel" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 156, gen: 2, names: { fr: "Feurisson", en: "Quilava", es: "Quilava", de: "Igelavar" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 157, gen: 2, names: { fr: "Typhlosion", en: "Typhlosion", es: "Typhlosion", de: "Tornupto" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 158, gen: 2, names: { fr: "Kaiminus", en: "Totodile", es: "Totodile", de: "Karnimani" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 159, gen: 2, names: { fr: "Crocrodil", en: "Croconaw", es: "Croconaw", de: "Tyracroc" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 160, gen: 2, names: { fr: "Aligatueur", en: "Feraligatr", es: "Feraligatr", de: "Impergator" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 161, gen: 2, names: { fr: "Fouinette", en: "Sentret", es: "Sentret", de: "Wiesor" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 162, gen: 2, names: { fr: "Fouinar", en: "Furret", es: "Furret", de: "Wiesenior" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 163, gen: 2, names: { fr: "Hoothoot", en: "Hoothoot", es: "Hoothoot", de: "Hoothoot" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"], de: ["Normal", "Flug"] } },
  { id: 164, gen: 2, names: { fr: "Noarfang", en: "Noctowl", es: "Noctowl", de: "Noctuh" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"], de: ["Normal", "Flug"] } },
  { id: 165, gen: 2, names: { fr: "Coxy", en: "Ledyba", es: "Ledyba", de: "Ledyba" }, types: { fr: ["Insecte", "Vol"], en: ["Bug", "Flying"], es: ["Bicho", "Volador"], de: ["Käfer", "Flug"] } },
  { id: 166, gen: 2, names: { fr: "Coxyclaque", en: "Ledian", es: "Ledian", de: "Ledian" }, types: { fr: ["Insecte", "Vol"], en: ["Bug", "Flying"], es: ["Bicho", "Volador"], de: ["Käfer", "Flug"] } },
  { id: 167, gen: 2, names: { fr: "Mimigal", en: "Spinarak", es: "Spinarak", de: "Webarak" }, types: { fr: ["Insecte", "Poison"], en: ["Bug", "Poison"], es: ["Bicho", "Veneno"], de: ["Käfer", "Gift"] } },
  { id: 168, gen: 2, names: { fr: "Migalos", en: "Ariados", es: "Ariados", de: "Ariados" }, types: { fr: ["Insecte", "Poison"], en: ["Bug", "Poison"], es: ["Bicho", "Veneno"], de: ["Käfer", "Gift"] } },
  { id: 169, gen: 2, names: { fr: "Nostenfer", en: "Crobat", es: "Crobat", de: "Iksbat" }, types: { fr: ["Poison", "Vol"], en: ["Poison", "Flying"], es: ["Veneno", "Volador"], de: ["Gift", "Flug"] } },
  { id: 170, gen: 2, names: { fr: "Loupio", en: "Chinchou", es: "Chinchou", de: "Lampi" }, types: { fr: ["Eau", "Électrik"], en: ["Water", "Electric"], es: ["Agua", "Eléctrico"], de: ["Wasser", "Elektro"] } },
  { id: 171, gen: 2, names: { fr: "Lanturn", en: "Lanturn", es: "Lanturn", de: "Lanturn" }, types: { fr: ["Eau", "Électrik"], en: ["Water", "Electric"], es: ["Agua", "Eléctrico"], de: ["Wasser", "Elektro"] } },
  { id: 172, gen: 2, names: { fr: "Pichu", en: "Pichu", es: "Pichu", de: "Pichu" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"], de: ["Elektro"] } },
  { id: 173, gen: 2, names: { fr: "Mélo", en: "Cleffa", es: "Cleffa", de: "Pii" }, types: { fr: ["Fée"], en: ["Fairy"], es: ["Hada"], de: ["Fee"] } },
  { id: 174, gen: 2, names: { fr: "Toudoudou", en: "Igglybuff", es: "Igglybuff", de: "Fluffeluff" }, types: { fr: ["Normal", "Fée"], en: ["Normal", "Fairy"], es: ["Normal", "Hada"], de: ["Normal", "Fee"] } },
  { id: 175, gen: 2, names: { fr: "Togepi", en: "Togepi", es: "Togepi", de: "Togepi" }, types: { fr: ["Fée"], en: ["Fairy"], es: ["Hada"], de: ["Fee"] } },
  { id: 176, gen: 2, names: { fr: "Togetic", en: "Togetic", es: "Togetic", de: "Togetic" }, types: { fr: ["Fée", "Vol"], en: ["Fairy", "Flying"], es: ["Hada", "Volador"], de: ["Fee", "Flug"] } },
  { id: 177, gen: 2, names: { fr: "Natu", en: "Natu", es: "Natu", de: "Natu" }, types: { fr: ["Psy", "Vol"], en: ["Psychic", "Flying"], es: ["Psíquico", "Volador"], de: ["Psycho", "Flug"] } },
  { id: 178, gen: 2, names: { fr: "Xatu", en: "Xatu", es: "Xatu", de: "Xatu" }, types: { fr: ["Psy", "Vol"], en: ["Psychic", "Flying"], es: ["Psíquico", "Volador"], de: ["Psycho", "Flug"] } },
  { id: 179, gen: 2, names: { fr: "Wattouat", en: "Mareep", es: "Mareep", de: "Voltilamm" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"], de: ["Elektro"] } },
  { id: 180, gen: 2, names: { fr: "Lainergie", en: "Flaaffy", es: "Flaaffy", de: "Waaty" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"], de: ["Elektro"] } },
  { id: 181, gen: 2, names: { fr: "Pharamp", en: "Ampharos", es: "Ampharos", de: "Ampharos" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"], de: ["Elektro"] } },
  { id: 182, gen: 2, names: { fr: "Joliflor", en: "Bellossom", es: "Bellossom", de: "Blubella" }, types: { fr: ["Plante"], en: ["Grass"], es: ["Planta"], de: ["Pflanze"] } },
  { id: 183, gen: 2, names: { fr: "Marill", en: "Marill", es: "Marill", de: "Marill" }, types: { fr: ["Eau", "Fée"], en: ["Water", "Fairy"], es: ["Agua", "Hada"], de: ["Wasser", "Fee"] } },
  { id: 184, gen: 2, names: { fr: "Azumarill", en: "Azumarill", es: "Azumarill", de: "Azumarill" }, types: { fr: ["Eau", "Fée"], en: ["Water", "Fairy"], es: ["Agua", "Hada"], de: ["Wasser", "Fee"] } },
  { id: 185, gen: 2, names: { fr: "Simularbre", en: "Sudowoodo", es: "Sudowoodo", de: "Mogelbaum" }, types: { fr: ["Roche"], en: ["Rock"], es: ["Roca"], de: ["Gestein"] } },
  { id: 186, gen: 2, names: { fr: "Tarpaud", en: "Politoed", es: "Politoed", de: "Quaxo" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 187, gen: 2, names: { fr: "Granivol", en: "Hoppip", es: "Hoppip", de: "Hoppspross" }, types: { fr: ["Plante", "Vol"], en: ["Grass", "Flying"], es: ["Planta", "Volador"], de: ["Pflanze", "Flug"] } },
  { id: 188, gen: 2, names: { fr: "Floravol", en: "Skiploom", es: "Skiploom", de: "Hubelupf" }, types: { fr: ["Plante", "Vol"], en: ["Grass", "Flying"], es: ["Planta", "Volador"], de: ["Pflanze", "Flug"] } },
  { id: 189, gen: 2, names: { fr: "Cotovol", en: "Jumpluff", es: "Jumpluff", de: "Papungha" }, types: { fr: ["Plante", "Vol"], en: ["Grass", "Flying"], es: ["Planta", "Volador"], de: ["Pflanze", "Flug"] } },
  { id: 190, gen: 2, names: { fr: "Capumain", en: "Aipom", es: "Aipom", de: "Griffel" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 191, gen: 2, names: { fr: "Tournegrin", en: "Sunkern", es: "Sunkern", de: "Sonnkern" }, types: { fr: ["Plante"], en: ["Grass"], es: ["Planta"], de: ["Pflanze"] } },
  { id: 192, gen: 2, names: { fr: "Héliatronc", en: "Sunflora", es: "Sunflora", de: "Sonnflora" }, types: { fr: ["Plante"], en: ["Grass"], es: ["Planta"], de: ["Pflanze"] } },
  { id: 193, gen: 2, names: { fr: "Yanma", en: "Yanma", es: "Yanma", de: "Yanma" }, types: { fr: ["Insecte", "Vol"], en: ["Bug", "Flying"], es: ["Bicho", "Volador"], de: ["Käfer", "Flug"] } },
  { id: 194, gen: 2, names: { fr: "Axoloto", en: "Wooper", es: "Wooper", de: "Felino" }, types: { fr: ["Eau", "Sol"], en: ["Water", "Ground"], es: ["Agua", "Tierra"], de: ["Wasser", "Boden"] } },
  { id: 195, gen: 2, names: { fr: "Maraiste", en: "Quagsire", es: "Quagsire", de: "Morlord" }, types: { fr: ["Eau", "Sol"], en: ["Water", "Ground"], es: ["Agua", "Tierra"], de: ["Wasser", "Boden"] } },
  { id: 196, gen: 2, names: { fr: "Mentali", en: "Espeon", es: "Espeon", de: "Psiana" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"], de: ["Psycho"] } },
  { id: 197, gen: 2, names: { fr: "Noctali", en: "Umbreon", es: "Umbreon", de: "Nachtara" }, types: { fr: ["Ténèbres"], en: ["Dark"], es: ["Siniestro"], de: ["Unlicht"] } },
  { id: 198, gen: 2, names: { fr: "Cornèbre", en: "Murkrow", es: "Murkrow", de: "Kramurx" }, types: { fr: ["Ténèbres", "Vol"], en: ["Dark", "Flying"], es: ["Siniestro", "Volador"], de: ["Unlicht", "Flug"] } },
  { id: 199, gen: 2, names: { fr: "Roigada", en: "Slowking", es: "Slowking", de: "Laschoking" }, types: { fr: ["Eau", "Psy"], en: ["Water", "Psychic"], es: ["Agua", "Psíquico"], de: ["Wasser", "Psycho"] } },
  { id: 200, gen: 2, names: { fr: "Feuforêve", en: "Misdreavus", es: "Misdreavus", de: "Traunfugil" }, types: { fr: ["Spectre"], en: ["Ghost"], es: ["Fantasma"], de: ["Geist"] } },
  { id: 201, gen: 2, names: { fr: "Zarbi", en: "Unown", es: "Unown", de: "Icognito" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"], de: ["Psycho"] } },
  { id: 202, gen: 2, names: { fr: "Qulbutoké", en: "Wobbuffet", es: "Wobbuffet", de: "Woingenau" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"], de: ["Psycho"] } },
  { id: 203, gen: 2, names: { fr: "Girafarig", en: "Girafarig", es: "Girafarig", de: "Girafarig" }, types: { fr: ["Normal", "Psy"], en: ["Normal", "Psychic"], es: ["Normal", "Psíquico"], de: ["Normal", "Psycho"] } },
  { id: 204, gen: 2, names: { fr: "Pomdepik", en: "Pineco", es: "Pineco", de: "Tannza" }, types: { fr: ["Insecte"], en: ["Bug"], es: ["Bicho"], de: ["Käfer"] } },
  { id: 205, gen: 2, names: { fr: "Foretress", en: "Forretress", es: "Forretress", de: "Forstellka" }, types: { fr: ["Insecte", "Acier"], en: ["Bug", "Steel"], es: ["Bicho", "Acero"], de: ["Käfer", "Stahl"] } },
  { id: 206, gen: 2, names: { fr: "Insolourdo", en: "Dunsparce", es: "Dunsparce", de: "Dummisel" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 207, gen: 2, names: { fr: "Scorplane", en: "Gligar", es: "Gligar", de: "Skorgla" }, types: { fr: ["Sol", "Vol"], en: ["Ground", "Flying"], es: ["Tierra", "Volador"], de: ["Boden", "Flug"] } },
  { id: 208, gen: 2, names: { fr: "Steelix", en: "Steelix", es: "Steelix", de: "Stahlos" }, types: { fr: ["Acier", "Sol"], en: ["Steel", "Ground"], es: ["Acero", "Tierra"], de: ["Stahl", "Boden"] } },
  { id: 209, gen: 2, names: { fr: "Snubbull", en: "Snubbull", es: "Snubbull", de: "Snubbull" }, types: { fr: ["Fée"], en: ["Fairy"], es: ["Hada"], de: ["Fee"] } },
  { id: 210, gen: 2, names: { fr: "Granbull", en: "Granbull", es: "Granbull", de: "Granbull" }, types: { fr: ["Fée"], en: ["Fairy"], es: ["Hada"], de: ["Fee"] } },
  { id: 211, gen: 2, names: { fr: "Qwilfish", en: "Qwilfish", es: "Qwilfish", de: "Baldorfish" }, types: { fr: ["Eau", "Poison"], en: ["Water", "Poison"], es: ["Agua", "Veneno"], de: ["Wasser", "Gift"] } },
  { id: 212, gen: 2, names: { fr: "Cizayox", en: "Scizor", es: "Scizor", de: "Scherox" }, types: { fr: ["Insecte", "Acier"], en: ["Bug", "Steel"], es: ["Bicho", "Acero"], de: ["Käfer", "Stahl"] } },
  { id: 213, gen: 2, names: { fr: "Caratroc", en: "Shuckle", es: "Shuckle", de: "Pottrott" }, types: { fr: ["Insecte", "Roche"], en: ["Bug", "Rock"], es: ["Bicho", "Roca"], de: ["Käfer", "Gestein"] } },
  { id: 214, gen: 2, names: { fr: "Scarhino", en: "Heracross", es: "Heracross", de: "Skaraborn" }, types: { fr: ["Insecte", "Combat"], en: ["Bug", "Fighting"], es: ["Bicho", "Lucha"], de: ["Käfer", "Kampf"] } },
  { id: 215, gen: 2, names: { fr: "Farfuret", en: "Sneasel", es: "Sneasel", de: "Sniebel" }, types: { fr: ["Ténèbres", "Glace"], en: ["Dark", "Ice"], es: ["Siniestro", "Hielo"], de: ["Unlicht", "Eis"] } },
  { id: 216, gen: 2, names: { fr: "Teddiursa", en: "Teddiursa", es: "Teddiursa", de: "Teddiursa" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 217, gen: 2, names: { fr: "Ursaring", en: "Ursaring", es: "Ursaring", de: "Ursaring" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 218, gen: 2, names: { fr: "Limagma", en: "Slugma", es: "Slugma", de: "Schneckmag" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 219, gen: 2, names: { fr: "Volcaropod", en: "Magcargo", es: "Magcargo", de: "Magcargo" }, types: { fr: ["Feu", "Roche"], en: ["Fire", "Rock"], es: ["Fuego", "Roca"], de: ["Feuer", "Gestein"] } },
  { id: 220, gen: 2, names: { fr: "Marcacrin", en: "Swinub", es: "Swinub", de: "Quiekel" }, types: { fr: ["Glace", "Sol"], en: ["Ice", "Ground"], es: ["Hielo", "Tierra"], de: ["Eis", "Boden"] } },
  { id: 221, gen: 2, names: { fr: "Cochignon", en: "Piloswine", es: "Piloswine", de: "Keifel" }, types: { fr: ["Glace", "Sol"], en: ["Ice", "Ground"], es: ["Hielo", "Tierra"], de: ["Eis", "Boden"] } },
  { id: 222, gen: 2, names: { fr: "Corayon", en: "Corsola", es: "Corsola", de: "Corasonn" }, types: { fr: ["Eau", "Roche"], en: ["Water", "Rock"], es: ["Agua", "Roca"], de: ["Wasser", "Gestein"] } },
  { id: 223, gen: 2, names: { fr: "Rémoraid", en: "Remoraid", es: "Remoraid", de: "Remoraid" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 224, gen: 2, names: { fr: "Octillery", en: "Octillery", es: "Octillery", de: "Octillery" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 225, gen: 2, names: { fr: "Cadoizo", en: "Delibird", es: "Delibird", de: "Botogel" }, types: { fr: ["Glace", "Vol"], en: ["Ice", "Flying"], es: ["Hielo", "Volador"], de: ["Eis", "Flug"] } },
  { id: 226, gen: 2, names: { fr: "Démanta", en: "Mantine", es: "Mantine", de: "Mantax" }, types: { fr: ["Eau", "Vol"], en: ["Water", "Flying"], es: ["Agua", "Volador"], de: ["Wasser", "Flug"] } },
  { id: 227, gen: 2, names: { fr: "Airmure", en: "Skarmory", es: "Skarmory", de: "Panzaeron" }, types: { fr: ["Acier", "Vol"], en: ["Steel", "Flying"], es: ["Acero", "Volador"], de: ["Stahl", "Flug"] } },
  { id: 228, gen: 2, names: { fr: "Malosse", en: "Houndour", es: "Houndour", de: "Hunduster" }, types: { fr: ["Ténèbres", "Feu"], en: ["Dark", "Fire"], es: ["Siniestro", "Fuego"], de: ["Unlicht", "Feuer"] } },
  { id: 229, gen: 2, names: { fr: "Démolosse", en: "Houndoom", es: "Houndoom", de: "Hundemon" }, types: { fr: ["Ténèbres", "Feu"], en: ["Dark", "Fire"], es: ["Siniestro", "Fuego"], de: ["Unlicht", "Feuer"] } },
  { id: 230, gen: 2, names: { fr: "Hyporoi", en: "Kingdra", es: "Kingdra", de: "Seedraking" }, types: { fr: ["Eau", "Dragon"], en: ["Water", "Dragon"], es: ["Agua", "Dragón"], de: ["Wasser", "Drache"] } },
  { id: 231, gen: 2, names: { fr: "Phanpy", en: "Phanpy", es: "Phanpy", de: "Phanpy" }, types: { fr: ["Sol"], en: ["Ground"], es: ["Tierra"], de: ["Boden"] } },
  { id: 232, gen: 2, names: { fr: "Donphan", en: "Donphan", es: "Donphan", de: "Donphan" }, types: { fr: ["Sol"], en: ["Ground"], es: ["Tierra"], de: ["Boden"] } },
  { id: 233, gen: 2, names: { fr: "Porygon2", en: "Porygon2", es: "Porygon2", de: "Porygon2" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 234, gen: 2, names: { fr: "Cerfrousse", en: "Stantler", es: "Stantler", de: "Damhirplex" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 235, gen: 2, names: { fr: "Queulorior", en: "Smeargle", es: "Smeargle", de: "Farbeagle" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 236, gen: 2, names: { fr: "Debugant", en: "Tyrogue", es: "Tyrogue", de: "Rabauz" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"], de: ["Kampf"] } },
  { id: 237, gen: 2, names: { fr: "Kapoera", en: "Hitmontop", es: "Hitmontop", de: "Kapoera" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"], de: ["Kampf"] } },
  { id: 238, gen: 2, names: { fr: "Lippouti", en: "Smoochum", es: "Smoochum", de: "Kussilla" }, types: { fr: ["Glace", "Psy"], en: ["Ice", "Psychic"], es: ["Hielo", "Psíquico"], de: ["Eis", "Psycho"] } },
  { id: 239, gen: 2, names: { fr: "Élekid", en: "Elekid", es: "Elekid", de: "Elekid" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"], de: ["Elektro"] } },
  { id: 240, gen: 2, names: { fr: "Magby", en: "Magby", es: "Magby", de: "Magby" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 241, gen: 2, names: { fr: "Écrémeuh", en: "Miltank", es: "Miltank", de: "Miltank" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 242, gen: 2, names: { fr: "Leuphorie", en: "Blissey", es: "Blissey", de: "Heiteira" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 243, gen: 2, names: { fr: "Raikou", en: "Raikou", es: "Raikou", de: "Raikou" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"], de: ["Elektro"] } },
  { id: 244, gen: 2, names: { fr: "Entei", en: "Entei", es: "Entei", de: "Entei" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 245, gen: 2, names: { fr: "Suicune", en: "Suicune", es: "Suicune", de: "Suicune" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 246, gen: 2, names: { fr: "Embrylex", en: "Larvitar", es: "Larvitar", de: "Larvitar" }, types: { fr: ["Roche", "Sol"], en: ["Rock", "Ground"], es: ["Roca", "Tierra"], de: ["Gestein", "Boden"] } },
  { id: 247, gen: 2, names: { fr: "Ymphect", en: "Pupitar", es: "Pupitar", de: "Pupitar" }, types: { fr: ["Roche", "Sol"], en: ["Rock", "Ground"], es: ["Roca", "Tierra"], de: ["Gestein", "Boden"] } },
  { id: 248, gen: 2, names: { fr: "Tyranocif", en: "Tyranitar", es: "Tyranitar", de: "Despotar" }, types: { fr: ["Roche", "Ténèbres"], en: ["Rock", "Dark"], es: ["Roca", "Siniestro"], de: ["Gestein", "Unlicht"] } },
  { id: 249, gen: 2, names: { fr: "Lugia", en: "Lugia", es: "Lugia", de: "Lugia" }, types: { fr: ["Psy", "Vol"], en: ["Psychic", "Flying"], es: ["Psíquico", "Volador"], de: ["Psycho", "Flug"] } },
  { id: 250, gen: 2, names: { fr: "Ho-Oh", en: "Ho-Oh", es: "Ho-Oh", de: "Ho-Oh" }, types: { fr: ["Feu", "Vol"], en: ["Fire", "Flying"], es: ["Fuego", "Volador"], de: ["Feuer", "Flug"] } },
  { id: 251, gen: 2, names: { fr: "Celebi", en: "Celebi", es: "Celebi", de: "Celebi" }, types: { fr: ["Psy", "Plante"], en: ["Psychic", "Grass"], es: ["Psíquico", "Planta"], de: ["Psycho", "Pflanze"] } },
  { id: 252, gen: 3, names: { fr: "Arcko", en: "Treecko", es: "Treecko", de: "Geckarbor" }, types: { fr: ["Plante"], en: ["Grass"], es: ["Planta"], de: ["Pflanze"] } },
  { id: 253, gen: 3, names: { fr: "Massko", en: "Grovyle", es: "Grovyle", de: "Reptain" }, types: { fr: ["Plante"], en: ["Grass"], es: ["Planta"], de: ["Pflanze"] } },
  { id: 254, gen: 3, names: { fr: "Jungko", en: "Sceptile", es: "Sceptile", de: "Gewaldro" }, types: { fr: ["Plante"], en: ["Grass"], es: ["Planta"], de: ["Pflanze"] } },
  { id: 255, gen: 3, names: { fr: "Poussifeu", en: "Torchic", es: "Torchic", de: "Flemmli" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 256, gen: 3, names: { fr: "Galifeu", en: "Combusken", es: "Combusken", de: "Jungglut" }, types: { fr: ["Feu", "Combat"], en: ["Fire", "Fighting"], es: ["Fuego", "Lucha"], de: ["Feuer", "Kampf"] } },
  { id: 257, gen: 3, names: { fr: "Braségali", en: "Blaziken", es: "Blaziken", de: "Lohgock" }, types: { fr: ["Feu", "Combat"], en: ["Fire", "Fighting"], es: ["Fuego", "Lucha"], de: ["Feuer", "Kampf"] } },
  { id: 258, gen: 3, names: { fr: "Gobou", en: "Mudkip", es: "Mudkip", de: "Hydropi" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 259, gen: 3, names: { fr: "Flobio", en: "Marshtomp", es: "Marshtomp", de: "Moorabbel" }, types: { fr: ["Eau", "Sol"], en: ["Water", "Ground"], es: ["Agua", "Tierra"], de: ["Wasser", "Boden"] } },
  { id: 260, gen: 3, names: { fr: "Laggron", en: "Swampert", es: "Swampert", de: "Sumpex" }, types: { fr: ["Eau", "Sol"], en: ["Water", "Ground"], es: ["Agua", "Tierra"], de: ["Wasser", "Boden"] } },
  { id: 261, gen: 3, names: { fr: "Medhyèna", en: "Poochyena", es: "Poochyena", de: "Fiffyen" }, types: { fr: ["Ténèbres"], en: ["Dark"], es: ["Siniestro"], de: ["Unlicht"] } },
  { id: 262, gen: 3, names: { fr: "Grahyèna", en: "Mightyena", es: "Mightyena", de: "Magnayen" }, types: { fr: ["Ténèbres"], en: ["Dark"], es: ["Siniestro"], de: ["Unlicht"] } },
  { id: 263, gen: 3, names: { fr: "Zigzaton", en: "Zigzagoon", es: "Zigzagoon", de: "Zigzachs" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 264, gen: 3, names: { fr: "Linéon", en: "Linoone", es: "Linoone", de: "Geradaks" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 265, gen: 3, names: { fr: "Chenipotte", en: "Wurmple", es: "Wurmple", de: "Waumpel" }, types: { fr: ["Insecte"], en: ["Bug"], es: ["Bicho"], de: ["Käfer"] } },
  { id: 266, gen: 3, names: { fr: "Armulys", en: "Silcoon", es: "Silcoon", de: "Schaloko" }, types: { fr: ["Insecte"], en: ["Bug"], es: ["Bicho"], de: ["Käfer"] } },
  { id: 267, gen: 3, names: { fr: "Charmillon", en: "Beautifly", es: "Beautifly", de: "Papinella" }, types: { fr: ["Insecte", "Vol"], en: ["Bug", "Flying"], es: ["Bicho", "Volador"], de: ["Käfer", "Flug"] } },
  { id: 268, gen: 3, names: { fr: "Blindalys", en: "Cascoon", es: "Cascoon", de: "Panekon" }, types: { fr: ["Insecte"], en: ["Bug"], es: ["Bicho"], de: ["Käfer"] } },
  { id: 269, gen: 3, names: { fr: "Papinox", en: "Dustox", es: "Dustox", de: "Pudox" }, types: { fr: ["Insecte", "Poison"], en: ["Bug", "Poison"], es: ["Bicho", "Veneno"], de: ["Käfer", "Gift"] } },
  { id: 270, gen: 3, names: { fr: "Nénupiot", en: "Lotad", es: "Lotad", de: "Loturzel" }, types: { fr: ["Eau", "Plante"], en: ["Water", "Grass"], es: ["Agua", "Planta"], de: ["Wasser", "Pflanze"] } },
  { id: 271, gen: 3, names: { fr: "Lombre", en: "Lombre", es: "Lombre", de: "Lombrero" }, types: { fr: ["Eau", "Plante"], en: ["Water", "Grass"], es: ["Agua", "Planta"], de: ["Wasser", "Pflanze"] } },
  { id: 272, gen: 3, names: { fr: "Ludicolo", en: "Ludicolo", es: "Ludicolo", de: "Kappalores" }, types: { fr: ["Eau", "Plante"], en: ["Water", "Grass"], es: ["Agua", "Planta"], de: ["Wasser", "Pflanze"] } },
  { id: 273, gen: 3, names: { fr: "Grainipiot", en: "Seedot", es: "Seedot", de: "Samurzel" }, types: { fr: ["Plante"], en: ["Grass"], es: ["Planta"], de: ["Pflanze"] } },
  { id: 274, gen: 3, names: { fr: "Pifeuil", en: "Nuzleaf", es: "Nuzleaf", de: "Blanas" }, types: { fr: ["Plante", "Ténèbres"], en: ["Grass", "Dark"], es: ["Planta", "Siniestro"], de: ["Pflanze", "Unlicht"] } },
  { id: 275, gen: 3, names: { fr: "Tengalice", en: "Shiftry", es: "Shiftry", de: "Tengulist" }, types: { fr: ["Plante", "Ténèbres"], en: ["Grass", "Dark"], es: ["Planta", "Siniestro"], de: ["Pflanze", "Unlicht"] } },
  { id: 276, gen: 3, names: { fr: "Nirondelle", en: "Taillow", es: "Taillow", de: "Schwalbini" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"], de: ["Normal", "Flug"] } },
  { id: 277, gen: 3, names: { fr: "Hélédelle", en: "Swellow", es: "Swellow", de: "Schwalboss" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"], de: ["Normal", "Flug"] } },
  { id: 278, gen: 3, names: { fr: "Goélise", en: "Wingull", es: "Wingull", de: "Wingull" }, types: { fr: ["Eau", "Vol"], en: ["Water", "Flying"], es: ["Agua", "Volador"], de: ["Wasser", "Flug"] } },
  { id: 279, gen: 3, names: { fr: "Bekipan", en: "Pelipper", es: "Pelipper", de: "Pelipper" }, types: { fr: ["Eau", "Vol"], en: ["Water", "Flying"], es: ["Agua", "Volador"], de: ["Wasser", "Flug"] } },
  { id: 280, gen: 3, names: { fr: "Tarsal", en: "Ralts", es: "Ralts", de: "Trasla" }, types: { fr: ["Psy", "Fée"], en: ["Psychic", "Fairy"], es: ["Psíquico", "Hada"], de: ["Psycho", "Fee"] } },
  { id: 281, gen: 3, names: { fr: "Kirlia", en: "Kirlia", es: "Kirlia", de: "Kirlia" }, types: { fr: ["Psy", "Fée"], en: ["Psychic", "Fairy"], es: ["Psíquico", "Hada"], de: ["Psycho", "Fee"] } },
  { id: 282, gen: 3, names: { fr: "Gardevoir", en: "Gardevoir", es: "Gardevoir", de: "Guardevoir" }, types: { fr: ["Psy", "Fée"], en: ["Psychic", "Fairy"], es: ["Psíquico", "Hada"], de: ["Psycho", "Fee"] } },
  { id: 283, gen: 3, names: { fr: "Arakdo", en: "Surskit", es: "Surskit", de: "Gehweiher" }, types: { fr: ["Insecte", "Eau"], en: ["Bug", "Water"], es: ["Bicho", "Agua"], de: ["Käfer", "Wasser"] } },
  { id: 284, gen: 3, names: { fr: "Maskadra", en: "Masquerain", es: "Masquerain", de: "Maskeregen" }, types: { fr: ["Insecte", "Vol"], en: ["Bug", "Flying"], es: ["Bicho", "Volador"], de: ["Käfer", "Flug"] } },
  { id: 285, gen: 3, names: { fr: "Balignon", en: "Shroomish", es: "Shroomish", de: "Knilz" }, types: { fr: ["Plante"], en: ["Grass"], es: ["Planta"], de: ["Pflanze"] } },
  { id: 286, gen: 3, names: { fr: "Chapignon", en: "Breloom", es: "Breloom", de: "Kapilz" }, types: { fr: ["Plante", "Combat"], en: ["Grass", "Fighting"], es: ["Planta", "Lucha"], de: ["Pflanze", "Kampf"] } },
  { id: 287, gen: 3, names: { fr: "Parecool", en: "Slakoth", es: "Slakoth", de: "Bummelz" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 288, gen: 3, names: { fr: "Vigoroth", en: "Vigoroth", es: "Vigoroth", de: "Muntier" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 289, gen: 3, names: { fr: "Monaflèmit", en: "Slaking", es: "Slaking", de: "Letarking" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 290, gen: 3, names: { fr: "Ningale", en: "Nincada", es: "Nincada", de: "Nincada" }, types: { fr: ["Insecte", "Sol"], en: ["Bug", "Ground"], es: ["Bicho", "Tierra"], de: ["Käfer", "Boden"] } },
  { id: 291, gen: 3, names: { fr: "Ninjask", en: "Ninjask", es: "Ninjask", de: "Ninjask" }, types: { fr: ["Insecte", "Vol"], en: ["Bug", "Flying"], es: ["Bicho", "Volador"], de: ["Käfer", "Flug"] } },
  { id: 292, gen: 3, names: { fr: "Munja", en: "Shedinja", es: "Shedinja", de: "Ninjatom" }, types: { fr: ["Insecte", "Spectre"], en: ["Bug", "Ghost"], es: ["Bicho", "Fantasma"], de: ["Käfer", "Geist"] } },
  { id: 293, gen: 3, names: { fr: "Chuchmur", en: "Whismur", es: "Whismur", de: "Flurmel" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 294, gen: 3, names: { fr: "Ramboum", en: "Loudred", es: "Loudred", de: "Krakeelo" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 295, gen: 3, names: { fr: "Brouhabam", en: "Exploud", es: "Exploud", de: "Krawumms" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 296, gen: 3, names: { fr: "Makuhita", en: "Makuhita", es: "Makuhita", de: "Makuhita" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"], de: ["Kampf"] } },
  { id: 297, gen: 3, names: { fr: "Hariyama", en: "Hariyama", es: "Hariyama", de: "Hariyama" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"], de: ["Kampf"] } },
  { id: 298, gen: 3, names: { fr: "Azurill", en: "Azurill", es: "Azurill", de: "Azurill" }, types: { fr: ["Normal", "Fée"], en: ["Normal", "Fairy"], es: ["Normal", "Hada"], de: ["Normal", "Fee"] } },
  { id: 299, gen: 3, names: { fr: "Tarinor", en: "Nosepass", es: "Nosepass", de: "Nasgnet" }, types: { fr: ["Roche"], en: ["Rock"], es: ["Roca"], de: ["Gestein"] } },
  { id: 300, gen: 3, names: { fr: "Skitty", en: "Skitty", es: "Skitty", de: "Eneco" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 301, gen: 3, names: { fr: "Delcatty", en: "Delcatty", es: "Delcatty", de: "Enekoro" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 302, gen: 3, names: { fr: "Ténéfix", en: "Sableye", es: "Sableye", de: "Zobiris" }, types: { fr: ["Ténèbres", "Spectre"], en: ["Dark", "Ghost"], es: ["Siniestro", "Fantasma"], de: ["Unlicht", "Geist"] } },
  { id: 303, gen: 3, names: { fr: "Mysdibule", en: "Mawile", es: "Mawile", de: "Flunkifer" }, types: { fr: ["Acier", "Fée"], en: ["Steel", "Fairy"], es: ["Acero", "Hada"], de: ["Stahl", "Fee"] } },
  { id: 304, gen: 3, names: { fr: "Galekid", en: "Aron", es: "Aron", de: "Stollunior" }, types: { fr: ["Acier", "Roche"], en: ["Steel", "Rock"], es: ["Acero", "Roca"], de: ["Stahl", "Gestein"] } },
  { id: 305, gen: 3, names: { fr: "Galegon", en: "Lairon", es: "Lairon", de: "Stollrak" }, types: { fr: ["Acier", "Roche"], en: ["Steel", "Rock"], es: ["Acero", "Roca"], de: ["Stahl", "Gestein"] } },
  { id: 306, gen: 3, names: { fr: "Galeking", en: "Aggron", es: "Aggron", de: "Stolloss" }, types: { fr: ["Acier", "Roche"], en: ["Steel", "Rock"], es: ["Acero", "Roca"], de: ["Stahl", "Gestein"] } },
  { id: 307, gen: 3, names: { fr: "Méditikka", en: "Meditite", es: "Meditite", de: "Meditie" }, types: { fr: ["Combat", "Psy"], en: ["Fighting", "Psychic"], es: ["Lucha", "Psíquico"], de: ["Kampf", "Psycho"] } },
  { id: 308, gen: 3, names: { fr: "Charmina", en: "Medicham", es: "Medicham", de: "Meditalis" }, types: { fr: ["Combat", "Psy"], en: ["Fighting", "Psychic"], es: ["Lucha", "Psíquico"], de: ["Kampf", "Psycho"] } },
  { id: 309, gen: 3, names: { fr: "Dynavolt", en: "Electrike", es: "Electrike", de: "Frizelbliz" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"], de: ["Elektro"] } },
  { id: 310, gen: 3, names: { fr: "Élecsprint", en: "Manectric", es: "Manectric", de: "Voltenso" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"], de: ["Elektro"] } },
  { id: 311, gen: 3, names: { fr: "Posipi", en: "Plusle", es: "Plusle", de: "Plusle" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"], de: ["Elektro"] } },
  { id: 312, gen: 3, names: { fr: "Négapi", en: "Minun", es: "Minun", de: "Minun" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"], de: ["Elektro"] } },
  { id: 313, gen: 3, names: { fr: "Muciole", en: "Volbeat", es: "Volbeat", de: "Volbeat" }, types: { fr: ["Insecte"], en: ["Bug"], es: ["Bicho"], de: ["Käfer"] } },
  { id: 314, gen: 3, names: { fr: "Lumivole", en: "Illumise", es: "Illumise", de: "Illumise" }, types: { fr: ["Insecte"], en: ["Bug"], es: ["Bicho"], de: ["Käfer"] } },
  { id: 315, gen: 3, names: { fr: "Rosélia", en: "Roselia", es: "Roselia", de: "Roselia" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"], de: ["Pflanze", "Gift"] } },
  { id: 316, gen: 3, names: { fr: "Gloupti", en: "Gulpin", es: "Gulpin", de: "Schluppuck" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"], de: ["Gift"] } },
  { id: 317, gen: 3, names: { fr: "Avaltout", en: "Swalot", es: "Swalot", de: "Schlukwech" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"], de: ["Gift"] } },
  { id: 318, gen: 3, names: { fr: "Carvanha", en: "Carvanha", es: "Carvanha", de: "Kanivanha" }, types: { fr: ["Eau", "Ténèbres"], en: ["Water", "Dark"], es: ["Agua", "Siniestro"], de: ["Wasser", "Unlicht"] } },
  { id: 319, gen: 3, names: { fr: "Sharpedo", en: "Sharpedo", es: "Sharpedo", de: "Tohaido" }, types: { fr: ["Eau", "Ténèbres"], en: ["Water", "Dark"], es: ["Agua", "Siniestro"], de: ["Wasser", "Unlicht"] } },
  { id: 320, gen: 3, names: { fr: "Wailmer", en: "Wailmer", es: "Wailmer", de: "Wailmer" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 321, gen: 3, names: { fr: "Wailord", en: "Wailord", es: "Wailord", de: "Wailord" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 322, gen: 3, names: { fr: "Chamallot", en: "Numel", es: "Numel", de: "Camaub" }, types: { fr: ["Feu", "Sol"], en: ["Fire", "Ground"], es: ["Fuego", "Tierra"], de: ["Feuer", "Boden"] } },
  { id: 323, gen: 3, names: { fr: "Camérupt", en: "Camerupt", es: "Camerupt", de: "Camerupt" }, types: { fr: ["Feu", "Sol"], en: ["Fire", "Ground"], es: ["Fuego", "Tierra"], de: ["Feuer", "Boden"] } },
  { id: 324, gen: 3, names: { fr: "Chartor", en: "Torkoal", es: "Torkoal", de: "Qurtel" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"], de: ["Feuer"] } },
  { id: 325, gen: 3, names: { fr: "Spoink", en: "Spoink", es: "Spoink", de: "Spoink" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"], de: ["Psycho"] } },
  { id: 326, gen: 3, names: { fr: "Groret", en: "Grumpig", es: "Grumpig", de: "Groink" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"], de: ["Psycho"] } },
  { id: 327, gen: 3, names: { fr: "Spinda", en: "Spinda", es: "Spinda", de: "Pandir" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 328, gen: 3, names: { fr: "Kraknoix", en: "Trapinch", es: "Trapinch", de: "Knacklion" }, types: { fr: ["Sol"], en: ["Ground"], es: ["Tierra"], de: ["Boden"] } },
  { id: 329, gen: 3, names: { fr: "Vibraninf", en: "Vibrava", es: "Vibrava", de: "Vibrava" }, types: { fr: ["Sol", "Dragon"], en: ["Ground", "Dragon"], es: ["Tierra", "Dragón"], de: ["Boden", "Drache"] } },
  { id: 330, gen: 3, names: { fr: "Libégon", en: "Flygon", es: "Flygon", de: "Libelldra" }, types: { fr: ["Sol", "Dragon"], en: ["Ground", "Dragon"], es: ["Tierra", "Dragón"], de: ["Boden", "Drache"] } },
  { id: 331, gen: 3, names: { fr: "Cacnea", en: "Cacnea", es: "Cacnea", de: "Tuska" }, types: { fr: ["Plante"], en: ["Grass"], es: ["Planta"], de: ["Pflanze"] } },
  { id: 332, gen: 3, names: { fr: "Cacturne", en: "Cacturne", es: "Cacturne", de: "Noktuska" }, types: { fr: ["Plante", "Ténèbres"], en: ["Grass", "Dark"], es: ["Planta", "Siniestro"], de: ["Pflanze", "Unlicht"] } },
  { id: 333, gen: 3, names: { fr: "Tylton", en: "Swablu", es: "Swablu", de: "Wablu" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"], de: ["Normal", "Flug"] } },
  { id: 334, gen: 3, names: { fr: "Altaria", en: "Altaria", es: "Altaria", de: "Altaria" }, types: { fr: ["Dragon", "Vol"], en: ["Dragon", "Flying"], es: ["Dragón", "Volador"], de: ["Drache", "Flug"] } },
  { id: 335, gen: 3, names: { fr: "Mangriff", en: "Zangoose", es: "Zangoose", de: "Sengo" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 336, gen: 3, names: { fr: "Séviper", en: "Seviper", es: "Seviper", de: "Vipitis" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"], de: ["Gift"] } },
  { id: 337, gen: 3, names: { fr: "Séléroc", en: "Lunatone", es: "Lunatone", de: "Lunastein" }, types: { fr: ["Roche", "Psy"], en: ["Rock", "Psychic"], es: ["Roca", "Psíquico"], de: ["Gestein", "Psycho"] } },
  { id: 338, gen: 3, names: { fr: "Solaroc", en: "Solrock", es: "Solrock", de: "Sonnfel" }, types: { fr: ["Roche", "Psy"], en: ["Rock", "Psychic"], es: ["Roca", "Psíquico"], de: ["Gestein", "Psycho"] } },
  { id: 339, gen: 3, names: { fr: "Barloche", en: "Barboach", es: "Barboach", de: "Schmerbe" }, types: { fr: ["Eau", "Sol"], en: ["Water", "Ground"], es: ["Agua", "Tierra"], de: ["Wasser", "Boden"] } },
  { id: 340, gen: 3, names: { fr: "Barbicha", en: "Whiscash", es: "Whiscash", de: "Welsar" }, types: { fr: ["Eau", "Sol"], en: ["Water", "Ground"], es: ["Agua", "Tierra"], de: ["Wasser", "Boden"] } },
  { id: 341, gen: 3, names: { fr: "Écrapince", en: "Corphish", es: "Corphish", de: "Krebscorps" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 342, gen: 3, names: { fr: "Colhomard", en: "Crawdaunt", es: "Crawdaunt", de: "Krebutack" }, types: { fr: ["Eau", "Ténèbres"], en: ["Water", "Dark"], es: ["Agua", "Siniestro"], de: ["Wasser", "Unlicht"] } },
  { id: 343, gen: 3, names: { fr: "Balbuto", en: "Baltoy", es: "Baltoy", de: "Puppance" }, types: { fr: ["Sol", "Psy"], en: ["Ground", "Psychic"], es: ["Tierra", "Psíquico"], de: ["Boden", "Psycho"] } },
  { id: 344, gen: 3, names: { fr: "Kaorine", en: "Claydol", es: "Claydol", de: "Lepumentas" }, types: { fr: ["Sol", "Psy"], en: ["Ground", "Psychic"], es: ["Tierra", "Psíquico"], de: ["Boden", "Psycho"] } },
  { id: 345, gen: 3, names: { fr: "Lilia", en: "Lileep", es: "Lileep", de: "Liliep" }, types: { fr: ["Roche", "Plante"], en: ["Rock", "Grass"], es: ["Roca", "Planta"], de: ["Gestein", "Pflanze"] } },
  { id: 346, gen: 3, names: { fr: "Vacilys", en: "Cradily", es: "Cradily", de: "Wielie" }, types: { fr: ["Roche", "Plante"], en: ["Rock", "Grass"], es: ["Roca", "Planta"], de: ["Gestein", "Pflanze"] } },
  { id: 347, gen: 3, names: { fr: "Anorith", en: "Anorith", es: "Anorith", de: "Anorith" }, types: { fr: ["Roche", "Insecte"], en: ["Rock", "Bug"], es: ["Roca", "Bicho"], de: ["Gestein", "Käfer"] } },
  { id: 348, gen: 3, names: { fr: "Armaldo", en: "Armaldo", es: "Armaldo", de: "Armaldo" }, types: { fr: ["Roche", "Insecte"], en: ["Rock", "Bug"], es: ["Roca", "Bicho"], de: ["Gestein", "Käfer"] } },
  { id: 349, gen: 3, names: { fr: "Barpau", en: "Feebas", es: "Feebas", de: "Barschwa" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 350, gen: 3, names: { fr: "Milobellus", en: "Milotic", es: "Milotic", de: "Milotic" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 351, gen: 3, names: { fr: "Morphéo", en: "Castform", es: "Castform", de: "Formeo" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 352, gen: 3, names: { fr: "Kecleon", en: "Kecleon", es: "Kecleon", de: "Kecleon" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"], de: ["Normal"] } },
  { id: 353, gen: 3, names: { fr: "Polichombr", en: "Shuppet", es: "Shuppet", de: "Shuppet" }, types: { fr: ["Spectre"], en: ["Ghost"], es: ["Fantasma"], de: ["Geist"] } },
  { id: 354, gen: 3, names: { fr: "Branette", en: "Banette", es: "Banette", de: "Banette" }, types: { fr: ["Spectre"], en: ["Ghost"], es: ["Fantasma"], de: ["Geist"] } },
  { id: 355, gen: 3, names: { fr: "Skelénox", en: "Duskull", es: "Duskull", de: "Zwirrlicht" }, types: { fr: ["Spectre"], en: ["Ghost"], es: ["Fantasma"], de: ["Geist"] } },
  { id: 356, gen: 3, names: { fr: "Téraclope", en: "Dusclops", es: "Dusclops", de: "Zwirrklop" }, types: { fr: ["Spectre"], en: ["Ghost"], es: ["Fantasma"], de: ["Geist"] } },
  { id: 357, gen: 3, names: { fr: "Tropius", en: "Tropius", es: "Tropius", de: "Tropius" }, types: { fr: ["Plante", "Vol"], en: ["Grass", "Flying"], es: ["Planta", "Volador"], de: ["Pflanze", "Flug"] } },
  { id: 358, gen: 3, names: { fr: "Éoko", en: "Chimecho", es: "Chimecho", de: "Palimpalim" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"], de: ["Psycho"] } },
  { id: 359, gen: 3, names: { fr: "Absol", en: "Absol", es: "Absol", de: "Absol" }, types: { fr: ["Ténèbres"], en: ["Dark"], es: ["Siniestro"], de: ["Unlicht"] } },
  { id: 360, gen: 3, names: { fr: "Okéoké", en: "Wynaut", es: "Wynaut", de: "Isso" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"], de: ["Psycho"] } },
  { id: 361, gen: 3, names: { fr: "Stalgamin", en: "Snorunt", es: "Snorunt", de: "Schneppke" }, types: { fr: ["Glace"], en: ["Ice"], es: ["Hielo"], de: ["Eis"] } },
  { id: 362, gen: 3, names: { fr: "Oniglali", en: "Glalie", es: "Glalie", de: "Firnontor" }, types: { fr: ["Glace"], en: ["Ice"], es: ["Hielo"], de: ["Eis"] } },
  { id: 363, gen: 3, names: { fr: "Obalie", en: "Spheal", es: "Spheal", de: "Seemops" }, types: { fr: ["Glace", "Eau"], en: ["Ice", "Water"], es: ["Hielo", "Agua"], de: ["Eis", "Wasser"] } },
  { id: 364, gen: 3, names: { fr: "Phogleur", en: "Sealeo", es: "Sealeo", de: "Seejong" }, types: { fr: ["Glace", "Eau"], en: ["Ice", "Water"], es: ["Hielo", "Agua"], de: ["Eis", "Wasser"] } },
  { id: 365, gen: 3, names: { fr: "Kaimorse", en: "Walrein", es: "Walrein", de: "Walraisa" }, types: { fr: ["Glace", "Eau"], en: ["Ice", "Water"], es: ["Hielo", "Agua"], de: ["Eis", "Wasser"] } },
  { id: 366, gen: 3, names: { fr: "Coquiperl", en: "Clamperl", es: "Clamperl", de: "Perlu" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 367, gen: 3, names: { fr: "Serpang", en: "Huntail", es: "Huntail", de: "Aalabyss" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 368, gen: 3, names: { fr: "Rosabyss", en: "Gorebyss", es: "Gorebyss", de: "Saganabyss" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 369, gen: 3, names: { fr: "Relicanth", en: "Relicanth", es: "Relicanth", de: "Relicanth" }, types: { fr: ["Eau", "Roche"], en: ["Water", "Rock"], es: ["Agua", "Roca"], de: ["Wasser", "Gestein"] } },
  { id: 370, gen: 3, names: { fr: "Lovdisc", en: "Luvdisc", es: "Luvdisc", de: "Liebiskus" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 371, gen: 3, names: { fr: "Draby", en: "Bagon", es: "Bagon", de: "Kindwurm" }, types: { fr: ["Dragon"], en: ["Dragon"], es: ["Dragón"], de: ["Drache"] } },
  { id: 372, gen: 3, names: { fr: "Drackhaus", en: "Shelgon", es: "Shelgon", de: "Draschel" }, types: { fr: ["Dragon"], en: ["Dragon"], es: ["Dragón"], de: ["Drache"] } },
  { id: 373, gen: 3, names: { fr: "Drattak", en: "Salamence", es: "Salamence", de: "Brutalanda" }, types: { fr: ["Dragon", "Vol"], en: ["Dragon", "Flying"], es: ["Dragón", "Volador"], de: ["Drache", "Flug"] } },
  { id: 374, gen: 3, names: { fr: "Terhal", en: "Beldum", es: "Beldum", de: "Tanhel" }, types: { fr: ["Acier", "Psy"], en: ["Steel", "Psychic"], es: ["Acero", "Psíquico"], de: ["Stahl", "Psycho"] } },
  { id: 375, gen: 3, names: { fr: "Métang", en: "Metang", es: "Metang", de: "Metang" }, types: { fr: ["Acier", "Psy"], en: ["Steel", "Psychic"], es: ["Acero", "Psíquico"], de: ["Stahl", "Psycho"] } },
  { id: 376, gen: 3, names: { fr: "Métalosse", en: "Metagross", es: "Metagross", de: "Metagross" }, types: { fr: ["Acier", "Psy"], en: ["Steel", "Psychic"], es: ["Acero", "Psíquico"], de: ["Stahl", "Psycho"] } },
  { id: 377, gen: 3, names: { fr: "Regirock", en: "Regirock", es: "Regirock", de: "Regirock" }, types: { fr: ["Roche"], en: ["Rock"], es: ["Roca"], de: ["Gestein"] } },
  { id: 378, gen: 3, names: { fr: "Regice", en: "Regice", es: "Regice", de: "Regice" }, types: { fr: ["Glace"], en: ["Ice"], es: ["Hielo"], de: ["Eis"] } },
  { id: 379, gen: 3, names: { fr: "Registeel", en: "Registeel", es: "Registeel", de: "Registeel" }, types: { fr: ["Acier"], en: ["Steel"], es: ["Acero"], de: ["Stahl"] } },
  { id: 380, gen: 3, names: { fr: "Latias", en: "Latias", es: "Latias", de: "Latias" }, types: { fr: ["Dragon", "Psy"], en: ["Dragon", "Psychic"], es: ["Dragón", "Psíquico"], de: ["Drache", "Psycho"] } },
  { id: 381, gen: 3, names: { fr: "Latios", en: "Latios", es: "Latios", de: "Latios" }, types: { fr: ["Dragon", "Psy"], en: ["Dragon", "Psychic"], es: ["Dragón", "Psíquico"], de: ["Drache", "Psycho"] } },
  { id: 382, gen: 3, names: { fr: "Kyogre", en: "Kyogre", es: "Kyogre", de: "Kyogre" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"], de: ["Wasser"] } },
  { id: 383, gen: 3, names: { fr: "Groudon", en: "Groudon", es: "Groudon", de: "Groudon" }, types: { fr: ["Sol"], en: ["Ground"], es: ["Tierra"], de: ["Boden"] } },
  { id: 384, gen: 3, names: { fr: "Rayquaza", en: "Rayquaza", es: "Rayquaza", de: "Rayquaza" }, types: { fr: ["Dragon", "Vol"], en: ["Dragon", "Flying"], es: ["Dragón", "Volador"], de: ["Drache", "Flug"] } },
  { id: 385, gen: 3, names: { fr: "Jirachi", en: "Jirachi", es: "Jirachi", de: "Jirachi" }, types: { fr: ["Acier", "Psy"], en: ["Steel", "Psychic"], es: ["Acero", "Psíquico"], de: ["Stahl", "Psycho"] } },
  { id: 386, gen: 3, names: { fr: "Deoxys", en: "Deoxys", es: "Deoxys", de: "Deoxys" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"], de: ["Psycho"] } },
];
