// Les 151 Pokémon de la génération 1 (noms français, types actuels)
const POKEMON_GEN1 = [
  { id: 1, name: "Bulbizarre", types: ["Plante", "Poison"] },
  { id: 2, name: "Herbizarre", types: ["Plante", "Poison"] },
  { id: 3, name: "Florizarre", types: ["Plante", "Poison"] },
  { id: 4, name: "Salamèche", types: ["Feu"] },
  { id: 5, name: "Reptincel", types: ["Feu"] },
  { id: 6, name: "Dracaufeu", types: ["Feu", "Vol"] },
  { id: 7, name: "Carapuce", types: ["Eau"] },
  { id: 8, name: "Carabaffe", types: ["Eau"] },
  { id: 9, name: "Tortank", types: ["Eau"] },
  { id: 10, name: "Chenipan", types: ["Insecte"] },
  { id: 11, name: "Chrysacier", types: ["Insecte"] },
  { id: 12, name: "Papilusion", types: ["Insecte", "Vol"] },
  { id: 13, name: "Aspicot", types: ["Insecte", "Poison"] },
  { id: 14, name: "Coconfort", types: ["Insecte", "Poison"] },
  { id: 15, name: "Dardargnan", types: ["Insecte", "Poison"] },
  { id: 16, name: "Roucool", types: ["Normal", "Vol"] },
  { id: 17, name: "Roucoups", types: ["Normal", "Vol"] },
  { id: 18, name: "Roucarnage", types: ["Normal", "Vol"] },
  { id: 19, name: "Rattata", types: ["Normal"] },
  { id: 20, name: "Rattatac", types: ["Normal"] },
  { id: 21, name: "Piafabec", types: ["Normal", "Vol"] },
  { id: 22, name: "Rapasdepic", types: ["Normal", "Vol"] },
  { id: 23, name: "Abo", types: ["Poison"] },
  { id: 24, name: "Arbok", types: ["Poison"] },
  { id: 25, name: "Pikachu", types: ["Électrik"] },
  { id: 26, name: "Raichu", types: ["Électrik"] },
  { id: 27, name: "Sabelette", types: ["Sol"] },
  { id: 28, name: "Sablaireau", types: ["Sol"] },
  { id: 29, name: "Nidoran♀", types: ["Poison"] },
  { id: 30, name: "Nidorina", types: ["Poison"] },
  { id: 31, name: "Nidoqueen", types: ["Poison", "Sol"] },
  { id: 32, name: "Nidoran♂", types: ["Poison"] },
  { id: 33, name: "Nidorino", types: ["Poison"] },
  { id: 34, name: "Nidoking", types: ["Poison", "Sol"] },
  { id: 35, name: "Mélofée", types: ["Fée"] },
  { id: 36, name: "Mélodelfe", types: ["Fée"] },
  { id: 37, name: "Goupix", types: ["Feu"] },
  { id: 38, name: "Feunard", types: ["Feu"] },
  { id: 39, name: "Rondoudou", types: ["Normal", "Fée"] },
  { id: 40, name: "Grodoudou", types: ["Normal", "Fée"] },
  { id: 41, name: "Nosferapti", types: ["Poison", "Vol"] },
  { id: 42, name: "Nosferalto", types: ["Poison", "Vol"] },
  { id: 43, name: "Mystherbe", types: ["Plante", "Poison"] },
  { id: 44, name: "Ortide", types: ["Plante", "Poison"] },
  { id: 45, name: "Rafflesia", types: ["Plante", "Poison"] },
  { id: 46, name: "Paras", types: ["Insecte", "Plante"] },
  { id: 47, name: "Parasect", types: ["Insecte", "Plante"] },
  { id: 48, name: "Mimitoss", types: ["Insecte", "Poison"] },
  { id: 49, name: "Aéromite", types: ["Insecte", "Poison"] },
  { id: 50, name: "Taupiqueur", types: ["Sol"] },
  { id: 51, name: "Triopikeur", types: ["Sol"] },
  { id: 52, name: "Miaouss", types: ["Normal"] },
  { id: 53, name: "Persian", types: ["Normal"] },
  { id: 54, name: "Psykokwak", types: ["Eau"] },
  { id: 55, name: "Akwakwak", types: ["Eau"] },
  { id: 56, name: "Férosinge", types: ["Combat"] },
  { id: 57, name: "Colossinge", types: ["Combat"] },
  { id: 58, name: "Caninos", types: ["Feu"] },
  { id: 59, name: "Arcanin", types: ["Feu"] },
  { id: 60, name: "Ptitard", types: ["Eau"] },
  { id: 61, name: "Têtarte", types: ["Eau"] },
  { id: 62, name: "Tartard", types: ["Eau", "Combat"] },
  { id: 63, name: "Abra", types: ["Psy"] },
  { id: 64, name: "Kadabra", types: ["Psy"] },
  { id: 65, name: "Alakazam", types: ["Psy"] },
  { id: 66, name: "Machoc", types: ["Combat"] },
  { id: 67, name: "Machopeur", types: ["Combat"] },
  { id: 68, name: "Mackogneur", types: ["Combat"] },
  { id: 69, name: "Chétiflor", types: ["Plante", "Poison"] },
  { id: 70, name: "Boustiflor", types: ["Plante", "Poison"] },
  { id: 71, name: "Empiflor", types: ["Plante", "Poison"] },
  { id: 72, name: "Tentacool", types: ["Eau", "Poison"] },
  { id: 73, name: "Tentacruel", types: ["Eau", "Poison"] },
  { id: 74, name: "Racaillou", types: ["Roche", "Sol"] },
  { id: 75, name: "Gravalanch", types: ["Roche", "Sol"] },
  { id: 76, name: "Grolem", types: ["Roche", "Sol"] },
  { id: 77, name: "Ponyta", types: ["Feu"] },
  { id: 78, name: "Galopa", types: ["Feu"] },
  { id: 79, name: "Ramoloss", types: ["Eau", "Psy"] },
  { id: 80, name: "Flagadoss", types: ["Eau", "Psy"] },
  { id: 81, name: "Magnéti", types: ["Électrik", "Acier"] },
  { id: 82, name: "Magnéton", types: ["Électrik", "Acier"] },
  { id: 83, name: "Canarticho", types: ["Normal", "Vol"] },
  { id: 84, name: "Doduo", types: ["Normal", "Vol"] },
  { id: 85, name: "Dodrio", types: ["Normal", "Vol"] },
  { id: 86, name: "Otaria", types: ["Eau"] },
  { id: 87, name: "Lamantine", types: ["Eau", "Glace"] },
  { id: 88, name: "Tadmorv", types: ["Poison"] },
  { id: 89, name: "Grotadmorv", types: ["Poison"] },
  { id: 90, name: "Kokiyas", types: ["Eau"] },
  { id: 91, name: "Crustabri", types: ["Eau", "Glace"] },
  { id: 92, name: "Fantominus", types: ["Spectre", "Poison"] },
  { id: 93, name: "Spectrum", types: ["Spectre", "Poison"] },
  { id: 94, name: "Ectoplasma", types: ["Spectre", "Poison"] },
  { id: 95, name: "Onix", types: ["Roche", "Sol"] },
  { id: 96, name: "Soporifik", types: ["Psy"] },
  { id: 97, name: "Hypnomade", types: ["Psy"] },
  { id: 98, name: "Krabby", types: ["Eau"] },
  { id: 99, name: "Krabboss", types: ["Eau"] },
  { id: 100, name: "Voltorbe", types: ["Électrik"] },
  { id: 101, name: "Électrode", types: ["Électrik"] },
  { id: 102, name: "Noeunoeuf", types: ["Plante", "Psy"] },
  { id: 103, name: "Noadkoko", types: ["Plante", "Psy"] },
  { id: 104, name: "Osselait", types: ["Sol"] },
  { id: 105, name: "Ossatueur", types: ["Sol"] },
  { id: 106, name: "Kicklee", types: ["Combat"] },
  { id: 107, name: "Tygnon", types: ["Combat"] },
  { id: 108, name: "Excelangue", types: ["Normal"] },
  { id: 109, name: "Smogo", types: ["Poison"] },
  { id: 110, name: "Smogogo", types: ["Poison"] },
  { id: 111, name: "Rhinocorne", types: ["Sol", "Roche"] },
  { id: 112, name: "Rhinoféros", types: ["Sol", "Roche"] },
  { id: 113, name: "Leveinard", types: ["Normal"] },
  { id: 114, name: "Saquedeneu", types: ["Plante"] },
  { id: 115, name: "Kangourex", types: ["Normal"] },
  { id: 116, name: "Hypotrempe", types: ["Eau"] },
  { id: 117, name: "Hypocéan", types: ["Eau"] },
  { id: 118, name: "Poissirène", types: ["Eau"] },
  { id: 119, name: "Poissoroy", types: ["Eau"] },
  { id: 120, name: "Stari", types: ["Eau"] },
  { id: 121, name: "Staross", types: ["Eau", "Psy"] },
  { id: 122, name: "M. Mime", types: ["Psy", "Fée"] },
  { id: 123, name: "Insécateur", types: ["Insecte", "Vol"] },
  { id: 124, name: "Lippoutou", types: ["Glace", "Psy"] },
  { id: 125, name: "Élektek", types: ["Électrik"] },
  { id: 126, name: "Magmar", types: ["Feu"] },
  { id: 127, name: "Scarabrute", types: ["Insecte"] },
  { id: 128, name: "Tauros", types: ["Normal"] },
  { id: 129, name: "Magicarpe", types: ["Eau"] },
  { id: 130, name: "Léviator", types: ["Eau", "Vol"] },
  { id: 131, name: "Lokhlass", types: ["Eau", "Glace"] },
  { id: 132, name: "Métamorph", types: ["Normal"] },
  { id: 133, name: "Évoli", types: ["Normal"] },
  { id: 134, name: "Aquali", types: ["Eau"] },
  { id: 135, name: "Voltali", types: ["Électrik"] },
  { id: 136, name: "Pyroli", types: ["Feu"] },
  { id: 137, name: "Porygon", types: ["Normal"] },
  { id: 138, name: "Amonita", types: ["Roche", "Eau"] },
  { id: 139, name: "Amonistar", types: ["Roche", "Eau"] },
  { id: 140, name: "Kabuto", types: ["Roche", "Eau"] },
  { id: 141, name: "Kabutops", types: ["Roche", "Eau"] },
  { id: 142, name: "Ptéra", types: ["Roche", "Vol"] },
  { id: 143, name: "Ronflex", types: ["Normal"] },
  { id: 144, name: "Artikodin", types: ["Glace", "Vol"] },
  { id: 145, name: "Électhor", types: ["Électrik", "Vol"] },
  { id: 146, name: "Sulfura", types: ["Feu", "Vol"] },
  { id: 147, name: "Minidraco", types: ["Dragon"] },
  { id: 148, name: "Draco", types: ["Dragon"] },
  { id: 149, name: "Dracolosse", types: ["Dragon", "Vol"] },
  { id: 150, name: "Mewtwo", types: ["Psy"] },
  { id: 151, name: "Mew", types: ["Psy"] },
];
