// Les 151 Pokémon de la génération 1 : noms et types localisés (FR/EN/ES).
const POKEMON_GEN1 = [
  { id: 1, names: { fr: "Bulbizarre", en: "Bulbasaur", es: "Bulbasaur" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"] } },
  { id: 2, names: { fr: "Herbizarre", en: "Ivysaur", es: "Ivysaur" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"] } },
  { id: 3, names: { fr: "Florizarre", en: "Venusaur", es: "Venusaur" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"] } },
  { id: 4, names: { fr: "Salamèche", en: "Charmander", es: "Charmander" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"] } },
  { id: 5, names: { fr: "Reptincel", en: "Charmeleon", es: "Charmeleon" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"] } },
  { id: 6, names: { fr: "Dracaufeu", en: "Charizard", es: "Charizard" }, types: { fr: ["Feu", "Vol"], en: ["Fire", "Flying"], es: ["Fuego", "Volador"] } },
  { id: 7, names: { fr: "Carapuce", en: "Squirtle", es: "Squirtle" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 8, names: { fr: "Carabaffe", en: "Wartortle", es: "Wartortle" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 9, names: { fr: "Tortank", en: "Blastoise", es: "Blastoise" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 10, names: { fr: "Chenipan", en: "Caterpie", es: "Caterpie" }, types: { fr: ["Insecte"], en: ["Bug"], es: ["Bicho"] } },
  { id: 11, names: { fr: "Chrysacier", en: "Metapod", es: "Metapod" }, types: { fr: ["Insecte"], en: ["Bug"], es: ["Bicho"] } },
  { id: 12, names: { fr: "Papilusion", en: "Butterfree", es: "Butterfree" }, types: { fr: ["Insecte", "Vol"], en: ["Bug", "Flying"], es: ["Bicho", "Volador"] } },
  { id: 13, names: { fr: "Aspicot", en: "Weedle", es: "Weedle" }, types: { fr: ["Insecte", "Poison"], en: ["Bug", "Poison"], es: ["Bicho", "Veneno"] } },
  { id: 14, names: { fr: "Coconfort", en: "Kakuna", es: "Kakuna" }, types: { fr: ["Insecte", "Poison"], en: ["Bug", "Poison"], es: ["Bicho", "Veneno"] } },
  { id: 15, names: { fr: "Dardargnan", en: "Beedrill", es: "Beedrill" }, types: { fr: ["Insecte", "Poison"], en: ["Bug", "Poison"], es: ["Bicho", "Veneno"] } },
  { id: 16, names: { fr: "Roucool", en: "Pidgey", es: "Pidgey" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"] } },
  { id: 17, names: { fr: "Roucoups", en: "Pidgeotto", es: "Pidgeotto" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"] } },
  { id: 18, names: { fr: "Roucarnage", en: "Pidgeot", es: "Pidgeot" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"] } },
  { id: 19, names: { fr: "Rattata", en: "Rattata", es: "Rattata" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"] } },
  { id: 20, names: { fr: "Rattatac", en: "Raticate", es: "Raticate" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"] } },
  { id: 21, names: { fr: "Piafabec", en: "Spearow", es: "Spearow" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"] } },
  { id: 22, names: { fr: "Rapasdepic", en: "Fearow", es: "Fearow" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"] } },
  { id: 23, names: { fr: "Abo", en: "Ekans", es: "Ekans" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"] } },
  { id: 24, names: { fr: "Arbok", en: "Arbok", es: "Arbok" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"] } },
  { id: 25, names: { fr: "Pikachu", en: "Pikachu", es: "Pikachu" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"] } },
  { id: 26, names: { fr: "Raichu", en: "Raichu", es: "Raichu" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"] } },
  { id: 27, names: { fr: "Sabelette", en: "Sandshrew", es: "Sandshrew" }, types: { fr: ["Sol"], en: ["Ground"], es: ["Tierra"] } },
  { id: 28, names: { fr: "Sablaireau", en: "Sandslash", es: "Sandslash" }, types: { fr: ["Sol"], en: ["Ground"], es: ["Tierra"] } },
  { id: 29, names: { fr: "Nidoran♀", en: "Nidoran♀", es: "Nidoran♀" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"] } },
  { id: 30, names: { fr: "Nidorina", en: "Nidorina", es: "Nidorina" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"] } },
  { id: 31, names: { fr: "Nidoqueen", en: "Nidoqueen", es: "Nidoqueen" }, types: { fr: ["Poison", "Sol"], en: ["Poison", "Ground"], es: ["Veneno", "Tierra"] } },
  { id: 32, names: { fr: "Nidoran♂", en: "Nidoran♂", es: "Nidoran♂" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"] } },
  { id: 33, names: { fr: "Nidorino", en: "Nidorino", es: "Nidorino" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"] } },
  { id: 34, names: { fr: "Nidoking", en: "Nidoking", es: "Nidoking" }, types: { fr: ["Poison", "Sol"], en: ["Poison", "Ground"], es: ["Veneno", "Tierra"] } },
  { id: 35, names: { fr: "Mélofée", en: "Clefairy", es: "Clefairy" }, types: { fr: ["Fée"], en: ["Fairy"], es: ["Hada"] } },
  { id: 36, names: { fr: "Mélodelfe", en: "Clefable", es: "Clefable" }, types: { fr: ["Fée"], en: ["Fairy"], es: ["Hada"] } },
  { id: 37, names: { fr: "Goupix", en: "Vulpix", es: "Vulpix" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"] } },
  { id: 38, names: { fr: "Feunard", en: "Ninetales", es: "Ninetales" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"] } },
  { id: 39, names: { fr: "Rondoudou", en: "Jigglypuff", es: "Jigglypuff" }, types: { fr: ["Normal", "Fée"], en: ["Normal", "Fairy"], es: ["Normal", "Hada"] } },
  { id: 40, names: { fr: "Grodoudou", en: "Wigglytuff", es: "Wigglytuff" }, types: { fr: ["Normal", "Fée"], en: ["Normal", "Fairy"], es: ["Normal", "Hada"] } },
  { id: 41, names: { fr: "Nosferapti", en: "Zubat", es: "Zubat" }, types: { fr: ["Poison", "Vol"], en: ["Poison", "Flying"], es: ["Veneno", "Volador"] } },
  { id: 42, names: { fr: "Nosferalto", en: "Golbat", es: "Golbat" }, types: { fr: ["Poison", "Vol"], en: ["Poison", "Flying"], es: ["Veneno", "Volador"] } },
  { id: 43, names: { fr: "Mystherbe", en: "Oddish", es: "Oddish" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"] } },
  { id: 44, names: { fr: "Ortide", en: "Gloom", es: "Gloom" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"] } },
  { id: 45, names: { fr: "Rafflesia", en: "Vileplume", es: "Vileplume" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"] } },
  { id: 46, names: { fr: "Paras", en: "Paras", es: "Paras" }, types: { fr: ["Insecte", "Plante"], en: ["Bug", "Grass"], es: ["Bicho", "Planta"] } },
  { id: 47, names: { fr: "Parasect", en: "Parasect", es: "Parasect" }, types: { fr: ["Insecte", "Plante"], en: ["Bug", "Grass"], es: ["Bicho", "Planta"] } },
  { id: 48, names: { fr: "Mimitoss", en: "Venonat", es: "Venonat" }, types: { fr: ["Insecte", "Poison"], en: ["Bug", "Poison"], es: ["Bicho", "Veneno"] } },
  { id: 49, names: { fr: "Aéromite", en: "Venomoth", es: "Venomoth" }, types: { fr: ["Insecte", "Poison"], en: ["Bug", "Poison"], es: ["Bicho", "Veneno"] } },
  { id: 50, names: { fr: "Taupiqueur", en: "Diglett", es: "Diglett" }, types: { fr: ["Sol"], en: ["Ground"], es: ["Tierra"] } },
  { id: 51, names: { fr: "Triopikeur", en: "Dugtrio", es: "Dugtrio" }, types: { fr: ["Sol"], en: ["Ground"], es: ["Tierra"] } },
  { id: 52, names: { fr: "Miaouss", en: "Meowth", es: "Meowth" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"] } },
  { id: 53, names: { fr: "Persian", en: "Persian", es: "Persian" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"] } },
  { id: 54, names: { fr: "Psykokwak", en: "Psyduck", es: "Psyduck" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 55, names: { fr: "Akwakwak", en: "Golduck", es: "Golduck" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 56, names: { fr: "Férosinge", en: "Mankey", es: "Mankey" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"] } },
  { id: 57, names: { fr: "Colossinge", en: "Primeape", es: "Primeape" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"] } },
  { id: 58, names: { fr: "Caninos", en: "Growlithe", es: "Growlithe" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"] } },
  { id: 59, names: { fr: "Arcanin", en: "Arcanine", es: "Arcanine" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"] } },
  { id: 60, names: { fr: "Ptitard", en: "Poliwag", es: "Poliwag" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 61, names: { fr: "Têtarte", en: "Poliwhirl", es: "Poliwhirl" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 62, names: { fr: "Tartard", en: "Poliwrath", es: "Poliwrath" }, types: { fr: ["Eau", "Combat"], en: ["Water", "Fighting"], es: ["Agua", "Lucha"] } },
  { id: 63, names: { fr: "Abra", en: "Abra", es: "Abra" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"] } },
  { id: 64, names: { fr: "Kadabra", en: "Kadabra", es: "Kadabra" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"] } },
  { id: 65, names: { fr: "Alakazam", en: "Alakazam", es: "Alakazam" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"] } },
  { id: 66, names: { fr: "Machoc", en: "Machop", es: "Machop" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"] } },
  { id: 67, names: { fr: "Machopeur", en: "Machoke", es: "Machoke" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"] } },
  { id: 68, names: { fr: "Mackogneur", en: "Machamp", es: "Machamp" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"] } },
  { id: 69, names: { fr: "Chétiflor", en: "Bellsprout", es: "Bellsprout" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"] } },
  { id: 70, names: { fr: "Boustiflor", en: "Weepinbell", es: "Weepinbell" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"] } },
  { id: 71, names: { fr: "Empiflor", en: "Victreebel", es: "Victreebel" }, types: { fr: ["Plante", "Poison"], en: ["Grass", "Poison"], es: ["Planta", "Veneno"] } },
  { id: 72, names: { fr: "Tentacool", en: "Tentacool", es: "Tentacool" }, types: { fr: ["Eau", "Poison"], en: ["Water", "Poison"], es: ["Agua", "Veneno"] } },
  { id: 73, names: { fr: "Tentacruel", en: "Tentacruel", es: "Tentacruel" }, types: { fr: ["Eau", "Poison"], en: ["Water", "Poison"], es: ["Agua", "Veneno"] } },
  { id: 74, names: { fr: "Racaillou", en: "Geodude", es: "Geodude" }, types: { fr: ["Roche", "Sol"], en: ["Rock", "Ground"], es: ["Roca", "Tierra"] } },
  { id: 75, names: { fr: "Gravalanch", en: "Graveler", es: "Graveler" }, types: { fr: ["Roche", "Sol"], en: ["Rock", "Ground"], es: ["Roca", "Tierra"] } },
  { id: 76, names: { fr: "Grolem", en: "Golem", es: "Golem" }, types: { fr: ["Roche", "Sol"], en: ["Rock", "Ground"], es: ["Roca", "Tierra"] } },
  { id: 77, names: { fr: "Ponyta", en: "Ponyta", es: "Ponyta" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"] } },
  { id: 78, names: { fr: "Galopa", en: "Rapidash", es: "Rapidash" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"] } },
  { id: 79, names: { fr: "Ramoloss", en: "Slowpoke", es: "Slowpoke" }, types: { fr: ["Eau", "Psy"], en: ["Water", "Psychic"], es: ["Agua", "Psíquico"] } },
  { id: 80, names: { fr: "Flagadoss", en: "Slowbro", es: "Slowbro" }, types: { fr: ["Eau", "Psy"], en: ["Water", "Psychic"], es: ["Agua", "Psíquico"] } },
  { id: 81, names: { fr: "Magnéti", en: "Magnemite", es: "Magnemite" }, types: { fr: ["Électrik", "Acier"], en: ["Electric", "Steel"], es: ["Eléctrico", "Acero"] } },
  { id: 82, names: { fr: "Magnéton", en: "Magneton", es: "Magneton" }, types: { fr: ["Électrik", "Acier"], en: ["Electric", "Steel"], es: ["Eléctrico", "Acero"] } },
  { id: 83, names: { fr: "Canarticho", en: "Farfetch’d", es: "Farfetch’d" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"] } },
  { id: 84, names: { fr: "Doduo", en: "Doduo", es: "Doduo" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"] } },
  { id: 85, names: { fr: "Dodrio", en: "Dodrio", es: "Dodrio" }, types: { fr: ["Normal", "Vol"], en: ["Normal", "Flying"], es: ["Normal", "Volador"] } },
  { id: 86, names: { fr: "Otaria", en: "Seel", es: "Seel" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 87, names: { fr: "Lamantine", en: "Dewgong", es: "Dewgong" }, types: { fr: ["Eau", "Glace"], en: ["Water", "Ice"], es: ["Agua", "Hielo"] } },
  { id: 88, names: { fr: "Tadmorv", en: "Grimer", es: "Grimer" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"] } },
  { id: 89, names: { fr: "Grotadmorv", en: "Muk", es: "Muk" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"] } },
  { id: 90, names: { fr: "Kokiyas", en: "Shellder", es: "Shellder" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 91, names: { fr: "Crustabri", en: "Cloyster", es: "Cloyster" }, types: { fr: ["Eau", "Glace"], en: ["Water", "Ice"], es: ["Agua", "Hielo"] } },
  { id: 92, names: { fr: "Fantominus", en: "Gastly", es: "Gastly" }, types: { fr: ["Spectre", "Poison"], en: ["Ghost", "Poison"], es: ["Fantasma", "Veneno"] } },
  { id: 93, names: { fr: "Spectrum", en: "Haunter", es: "Haunter" }, types: { fr: ["Spectre", "Poison"], en: ["Ghost", "Poison"], es: ["Fantasma", "Veneno"] } },
  { id: 94, names: { fr: "Ectoplasma", en: "Gengar", es: "Gengar" }, types: { fr: ["Spectre", "Poison"], en: ["Ghost", "Poison"], es: ["Fantasma", "Veneno"] } },
  { id: 95, names: { fr: "Onix", en: "Onix", es: "Onix" }, types: { fr: ["Roche", "Sol"], en: ["Rock", "Ground"], es: ["Roca", "Tierra"] } },
  { id: 96, names: { fr: "Soporifik", en: "Drowzee", es: "Drowzee" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"] } },
  { id: 97, names: { fr: "Hypnomade", en: "Hypno", es: "Hypno" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"] } },
  { id: 98, names: { fr: "Krabby", en: "Krabby", es: "Krabby" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 99, names: { fr: "Krabboss", en: "Kingler", es: "Kingler" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 100, names: { fr: "Voltorbe", en: "Voltorb", es: "Voltorb" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"] } },
  { id: 101, names: { fr: "Électrode", en: "Electrode", es: "Electrode" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"] } },
  { id: 102, names: { fr: "Noeunoeuf", en: "Exeggcute", es: "Exeggcute" }, types: { fr: ["Plante", "Psy"], en: ["Grass", "Psychic"], es: ["Planta", "Psíquico"] } },
  { id: 103, names: { fr: "Noadkoko", en: "Exeggutor", es: "Exeggutor" }, types: { fr: ["Plante", "Psy"], en: ["Grass", "Psychic"], es: ["Planta", "Psíquico"] } },
  { id: 104, names: { fr: "Osselait", en: "Cubone", es: "Cubone" }, types: { fr: ["Sol"], en: ["Ground"], es: ["Tierra"] } },
  { id: 105, names: { fr: "Ossatueur", en: "Marowak", es: "Marowak" }, types: { fr: ["Sol"], en: ["Ground"], es: ["Tierra"] } },
  { id: 106, names: { fr: "Kicklee", en: "Hitmonlee", es: "Hitmonlee" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"] } },
  { id: 107, names: { fr: "Tygnon", en: "Hitmonchan", es: "Hitmonchan" }, types: { fr: ["Combat"], en: ["Fighting"], es: ["Lucha"] } },
  { id: 108, names: { fr: "Excelangue", en: "Lickitung", es: "Lickitung" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"] } },
  { id: 109, names: { fr: "Smogo", en: "Koffing", es: "Koffing" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"] } },
  { id: 110, names: { fr: "Smogogo", en: "Weezing", es: "Weezing" }, types: { fr: ["Poison"], en: ["Poison"], es: ["Veneno"] } },
  { id: 111, names: { fr: "Rhinocorne", en: "Rhyhorn", es: "Rhyhorn" }, types: { fr: ["Sol", "Roche"], en: ["Ground", "Rock"], es: ["Tierra", "Roca"] } },
  { id: 112, names: { fr: "Rhinoféros", en: "Rhydon", es: "Rhydon" }, types: { fr: ["Sol", "Roche"], en: ["Ground", "Rock"], es: ["Tierra", "Roca"] } },
  { id: 113, names: { fr: "Leveinard", en: "Chansey", es: "Chansey" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"] } },
  { id: 114, names: { fr: "Saquedeneu", en: "Tangela", es: "Tangela" }, types: { fr: ["Plante"], en: ["Grass"], es: ["Planta"] } },
  { id: 115, names: { fr: "Kangourex", en: "Kangaskhan", es: "Kangaskhan" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"] } },
  { id: 116, names: { fr: "Hypotrempe", en: "Horsea", es: "Horsea" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 117, names: { fr: "Hypocéan", en: "Seadra", es: "Seadra" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 118, names: { fr: "Poissirène", en: "Goldeen", es: "Goldeen" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 119, names: { fr: "Poissoroy", en: "Seaking", es: "Seaking" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 120, names: { fr: "Stari", en: "Staryu", es: "Staryu" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 121, names: { fr: "Staross", en: "Starmie", es: "Starmie" }, types: { fr: ["Eau", "Psy"], en: ["Water", "Psychic"], es: ["Agua", "Psíquico"] } },
  { id: 122, names: { fr: "M. Mime", en: "Mr. Mime", es: "Mr. Mime" }, types: { fr: ["Psy", "Fée"], en: ["Psychic", "Fairy"], es: ["Psíquico", "Hada"] } },
  { id: 123, names: { fr: "Insécateur", en: "Scyther", es: "Scyther" }, types: { fr: ["Insecte", "Vol"], en: ["Bug", "Flying"], es: ["Bicho", "Volador"] } },
  { id: 124, names: { fr: "Lippoutou", en: "Jynx", es: "Jynx" }, types: { fr: ["Glace", "Psy"], en: ["Ice", "Psychic"], es: ["Hielo", "Psíquico"] } },
  { id: 125, names: { fr: "Élektek", en: "Electabuzz", es: "Electabuzz" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"] } },
  { id: 126, names: { fr: "Magmar", en: "Magmar", es: "Magmar" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"] } },
  { id: 127, names: { fr: "Scarabrute", en: "Pinsir", es: "Pinsir" }, types: { fr: ["Insecte"], en: ["Bug"], es: ["Bicho"] } },
  { id: 128, names: { fr: "Tauros", en: "Tauros", es: "Tauros" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"] } },
  { id: 129, names: { fr: "Magicarpe", en: "Magikarp", es: "Magikarp" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 130, names: { fr: "Léviator", en: "Gyarados", es: "Gyarados" }, types: { fr: ["Eau", "Vol"], en: ["Water", "Flying"], es: ["Agua", "Volador"] } },
  { id: 131, names: { fr: "Lokhlass", en: "Lapras", es: "Lapras" }, types: { fr: ["Eau", "Glace"], en: ["Water", "Ice"], es: ["Agua", "Hielo"] } },
  { id: 132, names: { fr: "Métamorph", en: "Ditto", es: "Ditto" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"] } },
  { id: 133, names: { fr: "Évoli", en: "Eevee", es: "Eevee" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"] } },
  { id: 134, names: { fr: "Aquali", en: "Vaporeon", es: "Vaporeon" }, types: { fr: ["Eau"], en: ["Water"], es: ["Agua"] } },
  { id: 135, names: { fr: "Voltali", en: "Jolteon", es: "Jolteon" }, types: { fr: ["Électrik"], en: ["Electric"], es: ["Eléctrico"] } },
  { id: 136, names: { fr: "Pyroli", en: "Flareon", es: "Flareon" }, types: { fr: ["Feu"], en: ["Fire"], es: ["Fuego"] } },
  { id: 137, names: { fr: "Porygon", en: "Porygon", es: "Porygon" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"] } },
  { id: 138, names: { fr: "Amonita", en: "Omanyte", es: "Omanyte" }, types: { fr: ["Roche", "Eau"], en: ["Rock", "Water"], es: ["Roca", "Agua"] } },
  { id: 139, names: { fr: "Amonistar", en: "Omastar", es: "Omastar" }, types: { fr: ["Roche", "Eau"], en: ["Rock", "Water"], es: ["Roca", "Agua"] } },
  { id: 140, names: { fr: "Kabuto", en: "Kabuto", es: "Kabuto" }, types: { fr: ["Roche", "Eau"], en: ["Rock", "Water"], es: ["Roca", "Agua"] } },
  { id: 141, names: { fr: "Kabutops", en: "Kabutops", es: "Kabutops" }, types: { fr: ["Roche", "Eau"], en: ["Rock", "Water"], es: ["Roca", "Agua"] } },
  { id: 142, names: { fr: "Ptéra", en: "Aerodactyl", es: "Aerodactyl" }, types: { fr: ["Roche", "Vol"], en: ["Rock", "Flying"], es: ["Roca", "Volador"] } },
  { id: 143, names: { fr: "Ronflex", en: "Snorlax", es: "Snorlax" }, types: { fr: ["Normal"], en: ["Normal"], es: ["Normal"] } },
  { id: 144, names: { fr: "Artikodin", en: "Articuno", es: "Articuno" }, types: { fr: ["Glace", "Vol"], en: ["Ice", "Flying"], es: ["Hielo", "Volador"] } },
  { id: 145, names: { fr: "Électhor", en: "Zapdos", es: "Zapdos" }, types: { fr: ["Électrik", "Vol"], en: ["Electric", "Flying"], es: ["Eléctrico", "Volador"] } },
  { id: 146, names: { fr: "Sulfura", en: "Moltres", es: "Moltres" }, types: { fr: ["Feu", "Vol"], en: ["Fire", "Flying"], es: ["Fuego", "Volador"] } },
  { id: 147, names: { fr: "Minidraco", en: "Dratini", es: "Dratini" }, types: { fr: ["Dragon"], en: ["Dragon"], es: ["Dragón"] } },
  { id: 148, names: { fr: "Draco", en: "Dragonair", es: "Dragonair" }, types: { fr: ["Dragon"], en: ["Dragon"], es: ["Dragón"] } },
  { id: 149, names: { fr: "Dracolosse", en: "Dragonite", es: "Dragonite" }, types: { fr: ["Dragon", "Vol"], en: ["Dragon", "Flying"], es: ["Dragón", "Volador"] } },
  { id: 150, names: { fr: "Mewtwo", en: "Mewtwo", es: "Mewtwo" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"] } },
  { id: 151, names: { fr: "Mew", en: "Mew", es: "Mew" }, types: { fr: ["Psy"], en: ["Psychic"], es: ["Psíquico"] } },
];
